### ISSUE TITLE
PyTables 3.8.0 install fail, h5 dependency?

### ISSUE THREAD

**Issue by mattgillam** [PyTables/PyTables#1082]
Hello, I am attempting to install a project that specifies tables==3..8.0 in requirements.txt

I've spent some time searching for a fix with no positive result, can anyone advise? Thank you.

```
Collecting tables==3.8.0 (from -r requirements.txt (line 23))
  Using cached tables-3.8.0.tar.gz (8.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]
      <string>:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      ld: library 'lzo2' not found
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      ld: library 'lzo' not found
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      ld: library 'blosc' not found
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      
      def _dump_h5_backtrace():
          cdef object bt = []
      
          if H5Ewalk(H5E_DEFAULT, H5E_WALK_DOWNWARD, e_walk_cb, <void*>bt) < 0:
                                                     ^
      ------------------------------------------------------------
      
      tables/utilsextension.pyx:384:47: Cannot assign type 'herr_t (unsigned int, const H5E_error_t *, void *) except? -1 nogil' to 'H5E_walk_t'. Exception values are incompatible. Suggest adding 'noexcept' to type 'herr_t (unsigned int, const H5E_error_t *, void *) except? -1 nogil'.
      cpuinfo failed, assuming no CPU features: 'flags'
      * Using Python 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]
      * Found cython 3.0.5
      * USE_PKGCONFIG: False
      * Found HDF5 headers at ``/opt/homebrew/include``, library at ``/opt/homebrew/lib``.
      * Could not find LZO 2 headers and library; disabling support for it.
      * Could not find LZO 1 headers and library; disabling support for it.
      * Could not find bzip2 headers and library; disabling support for it.
      * Could not find blosc headers and library; using internal sources.
      * Found blosc2 headers at ``/private/var/folders/tc/7rq5ktyj5k5fd66fb1lvrlq80000gn/T/pip-build-env-0ezpccmt/overlay/include``, library at ``/private/var/folders/tc/7rq5ktyj5k5fd66fb1lvrlq80000gn/T/pip-build-env-0ezpccmt/overlay/lib``.
        * Copying blosc2 runtime library to 'tables' dir because it was not found in standard locations
      Compiling tables/utilsextension.pyx because it changed.
      [1/1] Cythonizing tables/utilsextension.pyx
      Traceback (most recent call last):
        File "/Users/matt/dev/crypto/ft_local/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/matt/dev/crypto/ft_local/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/matt/dev/crypto/ft_local/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/tc/7rq5ktyj5k5fd66fb1lvrlq80000gn/T/pip-build-env-0ezpccmt/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/tc/7rq5ktyj5k5fd66fb1lvrlq80000gn/T/pip-build-env-0ezpccmt/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/tc/7rq5ktyj5k5fd66fb1lvrlq80000gn/T/pip-build-env-0ezpccmt/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 928, in <module>
        File "<string>", line 923, in get_cython_extfiles
        File "/private/var/folders/tc/7rq5ktyj5k5fd66fb1lvrlq80000gn/T/pip-build-env-0ezpccmt/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/tc/7rq5ktyj5k5fd66fb1lvrlq80000gn/T/pip-build-env-0ezpccmt/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: tables/utilsextension.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Failed installing dependencies
```

attempted using pip3 ->

```
$ pip3 install tables==3.8.0

Collecting tables==3.8.0
  Using cached tables-3.8.0.tar.gz (8.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      <string>:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      ld: library 'hdf5' not found
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      cpuinfo failed, assuming no CPU features: 'flags'
      * Using Python 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]
      * Found cython 3.0.5
      * USE_PKGCONFIG: False
      .. ERROR:: Could not find a local HDF5 installation.
         You may need to explicitly state where your local HDF5 headers and
         library can be found by setting the ``HDF5_DIR`` environment
         variable or by using the ``--hdf5`` command-line option.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by avalentino** [comment]
You should have a working installation of the HDF5 library (with the corresponding header files) to be able to install PyTables (see http://www.pytables.org/usersguide/installation.html).

**Comment by mattgillam** [comment]
My issue is a duplicate of https://github.com/PyTables/PyTables/issues/1040

I have installed the current version of PyTables 3.9.2.dev0 (via ``` pip3 install git+https://github.com/PyTables/PyTables```) and amended the dependent project's requirements in the hope if meets the need.
