### ISSUE TITLE
Corruption sometimes when repacking with blosc2?

### ISSUE THREAD

**Issue by chris-allan** [PyTables/PyTables#1086]
I've been experimenting with compression techniques with some of our existing PyTables data and noticed that if I repack with blosc2 the data is no longer readable. Files are available here:

* https://downloads.glencoesoftware.com/public/16731
* https://downloads.glencoesoftware.com/public/16731_blosc_zstd
* https://downloads.glencoesoftware.com/public/16731_blosc2_zstd

Repacking was performed with the following:

* `ptrepack --complib 'blosc2:zstd' --complevel '1' '16731:/' '16731_blosc2_zstd:/'`
* `ptrepack --complib 'blosc:zstd' --complevel '1' '16731:/' '16731_blosc_zstd:/'`

Opening the blosc2 compressed data like so:

```
import tables
a = tables.open_file('16731_blosc2_zstd', mode='r')
measurements = a.root.OME.Measurements
measurements[0]
```

Results in:

```
---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)
Cell In[5], line 1
----> 1 measurements[0]

File ~/OMERO.venv/lib/python3.10/site-packages/tables/table.py:2045, in Table.__getitem__(self, key)
   2043         key += self.nrows
   2044     (start, stop, step) = self._process_range(key, key + 1, 1)
-> 2045     return self.read(start, stop, step)[0]
   2046 elif isinstance(key, slice):
   2047     (start, stop, step) = self._process_range(
   2048         key.start, key.stop, key.step)

File ~/OMERO.venv/lib/python3.10/site-packages/tables/table.py:1900, in Table.read(self, start, stop, step, field, out)
   1895     raise TypeError(msg)
   1897 start, stop, step = self._process_range(start, stop, step,
   1898                                         warn_negstep=False)
-> 1900 arr = self._read(start, stop, step, field, out)
   1901 return internal_to_flavor(arr, self.flavor)

File ~/OMERO.venv/lib/python3.10/site-packages/tables/table.py:1814, in Table._read(self, start, stop, step, field, out)
   1810 # Call the routine to fill-up the resulting array
   1811 if step == 1 and not field:
   1812     # This optimization works three times faster than
   1813     # the row._fill_col method (up to 170 MB/s on a pentium IV @ 2GHz)
-> 1814     self._read_records(start, stop - start, result)
   1815 # Warning!: _read_field_name should not be used until
   1816 # H5TBread_fields_name in tableextension will be finished
   1817 # F. Alted 2005/05/26
   1818 # XYX Ho implementem per a PyTables 2.0??
   1819 elif field and step > 15 and 0:
   1820     # For step>15, this seems to work always faster than row._fill_col.

File ~/OMERO.venv/lib/python3.10/site-packages/tables/tableextension.pyx:645, in tables.tableextension.Table._read_records()

HDF5ExtError: HDF5 error back trace

  File "H5D.c", line 1061, in H5Dread
    can't synchronously read data
  File "H5D.c", line 1008, in H5D__read_api_common
    can't read data
  File "H5VLcallback.c", line 2092, in H5VL_dataset_read_direct
    dataset read failed
  File "H5VLcallback.c", line 2048, in H5VL__dataset_read
    dataset read failed
  File "H5VLnative_dataset.c", line 363, in H5VL__native_dataset_read
    can't read data
  File "H5Dio.c", line 383, in H5D__read
    can't read data
  File "H5Dchunk.c", line 2856, in H5D__chunk_read
    unable to read raw data chunk
  File "H5Dchunk.c", line 4468, in H5D__chunk_lock
    data pipeline read failed
  File "H5Z.c", line 1391, in H5Z_pipeline
    filter returned failure during read
  File "hdf5-blosc2/src/blosc2_filter.c", line 458, in blosc2_filter
    Cannot get super-chunk from buffer

End of HDF5 error back trace

Problems reading records.
```

Switching the compression type to `lz4` or `zlib` yields the same behaviour.

Repacking other trivial datasets that follow the same layout are fine. These files are available here:

* https://downloads.glencoesoftware.com/public/18546
* https://downloads.glencoesoftware.com/public/18546_blosc_zstd
* https://downloads.glencoesoftware.com/public/18546_blosc2_zstd

PyTables version is 3.9.2 with `blosc2==2.3.1` and running on Python 3.10 and Ubuntu 22.04 x86_64.

**Comment by ivilata** [comment]
Thanks @chris-allan for the report, sorry to hear that you have this problem.

I was able to reproduce the same error, even with `BLOSC2_FILTER=1` (optimizations disabled, HDF5 filter pipeline used), which suggests that it's being triggered [here](https://github.com/PyTables/PyTables/blob/06279116025647c708d7b64a0ebde24d75dfac49/src/H5TB-opt.c#L364). With `BLOSC_TRACE=1` I get the two extra diagnostic lines from C-Blosc2 right before the traceback:

```
[error] - `typesize` is zero or greater than max allowed. (/project/blosc2/c-blosc2/blosc/frame.c:432)
[error] - Unable to get meta info from frame. (/project/blosc2/c-blosc2/blosc/frame.c:1744)
```

I used `h5dump` to get filter arguments:

```
$ h5dump -pHd /OME/Measurements 16731_blosc2_zstd.h5 | grep -C4 FILTERS
   STORAGE_LAYOUT {
      CHUNKED ( 34 )
      SIZE 217016 (3.779:1 COMPRESSION)
   }
   FILTERS {
      USER_DEFINED_FILTER {
         FILTER_ID 32026
         COMMENT blosc2
         PARAMS { 1 30800 3850 130900 1 1 5 }
      }
   }
```

Filter parameters seem to be ok:

```
>>> measurements.dtype.itemsize
3850
>>> numpy.prod(measurements.chunkshape) * measurements.dtype.itemsize
130900
>>> 30800 / measurements.dtype.itemsize
8.0
```

Checking the typesize which Blosc2 complains about in [frame.c:432](https://github.com/Blosc/c-blosc2/blob/182f5571d88b87307993e01a32d0a36f1606f627/blosc/frame.c#L432), it should be between 1 and [BLOSC_MAX_TYPESIZE](https://github.com/Blosc/c-blosc2/blob/182f5571d88b87307993e01a32d0a36f1606f627/include/blosc2.h#L189), which is 255. In the table, the type size is 3850 > 255, hence the error.

I'm passing it on to @FrancescAlted in case he may suggest some path of action or workaround.

**Comment by chris-allan** [comment]
Thank, @ivilata. I have lots of data that exhibits the problem after repacking so if you need additional information let me know.

Based on your initial work I wonder if the problem is either (a) the number of columns (there are 323) or (b) the polygon string column. I'll see if I can restructure the data to check both of these. I also need to see if I can assert if the issue here is from repacking or not.

**Comment by FrancescAlted** [comment]
BTW, I have updated the C-Blosc2 submodule in the [Python-Blosc2 project](https://github.com/Blosc/python-blosc2/) for using the latest fix.  @chris-allan it would be nice if you can compile it locally (you can easily create a wheel with e.g. `CIBW_BUILD_VERBOSITY=1 python -m cibuildwheel --only 'cp312-manylinux_x86_64'`), install it and recompile PyTables against this one.  In case this does not fix the issue, please tell us.

**Comment by chris-allan** [comment]
Thanks, @FrancescAlted. I'll have a look as soon as I have some free cycles.

Looking at Blosc/c-blosc2@eeac9ec392103e428b808876b67dec2eb94e1aa6 I noticed that #1081 is referenced in the changelog. Is that correct?

**Comment by chris-allan** [comment]
Ah, nevermind, ignore me. It got changed later on with Blosc/c-blosc2@211e5a9.

**Comment by chris-allan** [comment]
@FrancescAlted: With me using `tables-3.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` building python-blosc2 separately will not work as it includes its own copy of c-blosc2, right?

```
$ unzip -l tables-3.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl | grep 'libblosc2'
  1855977  2023-11-27 08:28   tables.libs/libblosc2-6cd58c8e.so.2
  1842584  2023-11-27 08:28   tables/libblosc2.so
```

(Sidebar: Not sure why the library is included in the wheel twice)

**Comment by FrancescAlted** [comment]
That's right:

```
$ ldd /home/faltet/miniconda3/lib/python3.9/site-packages/tables/tableextension.cpython-39-x86_64-linux-gnu.so
<snip>
	libhdf5-23f9628c.so.310.2.0 => /home/faltet/miniconda3/lib/python3.9/site-packages/tables/../tables.libs/libhdf5-23f9628c.so.310.2.0 (0x00007fe4f4800000)
	libblosc2-81b65034.so.2 => /home/faltet/miniconda3/lib/python3.9/site-packages/tables/../tables.libs/libblosc2-81b65034.so.2 (0x00007fe4f4641000)
<snip>
```

Regarding whether PyTables wheel should include their own binary dependencies or not, it is debatable, but I tend to like all the binary dependencies (HDF5, Blosc2...) wrapped in the same wheel.  I know this can spark some discussion, but this is how things are right now.

**Comment by chris-allan** [comment]
Definitely didn't want to start a debate here about which dynamic libraries to include in the wheel. My only reason for bringing it up is that I built and installed python-blosc2 as you outlined and then was trying to figure out why I was getting exactly the same error even after removing python-blosc2 from my virtualenv entirely.

I've built c-blosc2 separately from Blosc/c-blosc2@211e5a95628e4c5f45e149a3c0ec29a655b5f55f and have just replaced the library by hand inside my virtualenv with good results. I can now read rows from the table that has been repacked with blosc2. At least to me I think we can consider the original issue I raised resolved. Thanks for all the work that went into this!

In case anyone is curious, I only had to replace `tables.libs/libblosc2-6cd58c8e.so.2` and not `tables/libblosc2.so` (I can't find anything that links to this) from the `tables` wheel. Again, not sure why its included in two different places in the same wheel. Happy to help with that separately if it's useful.

**Comment by FrancescAlted** [comment]
Cool!  Thanks @chris-allan  

And definitely, if you find ways to streamline the wheels or make them more consistent, your contribution is very welcome indeed.

**Comment by FrancescAlted** [comment]
Recently released versions of [C-Blosc2](https://github.com/Blosc/c-blosc2/releases/tag/v2.11.3) and [Python-Blosc2](https://github.com/Blosc/python-blosc2/releases/tag/v2.3.2) should fix this issue.  I'm going to close this, as the next release of PyTables will inherit the fix.
