### ISSUE TITLE
`tables.tests.test_direct_chunk` test regression with PyPy3.10 7.3.16

### ISSUE THREAD

**Issue by mgorny** [PyTables/PyTables#1202]
The 3.10.0 release seems to introduce test regressions on PyPy3.10 7.3.16. The tests used to pass with 3.9.2. I can reproduce on top of git master (2b03e35c7748fda20faa1083a052a8e2c5352320), both with NumPy 1.26.4 and 2.1.0rc1 (the errors are exactly the same).

```pytb
$ PYTHONPATH=. pypy3 tables/tests/test_all.py
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.10.1.dev0
HDF5 version:        1.14.4-2
NumPy version:       2.1.0rc1
Numexpr version:     2.10.1 (not using Intel's VML/MKL)
Zlib version:        1.3 (in Python interpreter)
LZO version:         2.10 (Mar 01 2017)
BZIP2 version:       1.0.8 (13-Jul-2019)
Blosc version:       1.21.6 (2024-06-24)
Blosc compressors:   blosclz (2.5.1), lz4 (1.10.0), lz4hc (1.10.0), snappy (unknown), zlib (1.3.1), zstd (1.5.6)
Blosc filters:       shuffle, bitshuffle
Blosc2 version:      2.15.1 (2024-07-30)
Blosc2 compressors:  blosclz (2.5.3), lz4 (1.10.0), lz4hc (1.10.0), zlib (1.3.1), zstd (1.5.6)
Blosc2 filters:      shuffle, bitshuffle
Cython version:      3.0.11
Python version:      3.10.14 (75b3de9d9035, Apr 24 2024, 12:29:25)
[PyPy 7.3.16 with GCC 13.2.1 20240210]
Platform:            Linux-6.10.4-gentoo-dist-x86_64-AMD_Ryzen_5_3600_6-Core_Processor-with-glibc2.40
Byte-ordering:       little
Detected cores:      12
Default encoding:    utf-8
Default FS encoding: utf-8
Default locale:      (pl_PL, UTF-8)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Performing only a light (yet comprehensive) subset of the test suite.
If you want a more complete test, try passing the --heavy flag to this script
(or set the 'heavy' parameter in case you are using tables.test() call).
The whole suite will take more than 4 hours to complete on a relatively
modern CPU and around 512 MB of main memory.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[…]
======================================================================
ERROR: None (tables.tests.test_direct_chunk.EArrayDirectChunkingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/PyTables/tables/tests/test_direct_chunk.py", line 266, in test_write_chunk_missing1
    return self._test_write_chunk_missing(shrink_after=False)
  File "/tmp/PyTables/tables/tests/test_direct_chunk.py", line 255, in _test_write_chunk_missing
    new_obj.resize(self.array.shape)
ValueError: cannot resize an array with refcheck=True on PyPy.
Use the np.resize function or refcheck=False

======================================================================
ERROR: None (tables.tests.test_direct_chunk.EArrayDirectChunkingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/PyTables/tables/tests/test_direct_chunk.py", line 269, in test_write_chunk_missing2
    return self._test_write_chunk_missing(shrink_after=True)
  File "/tmp/PyTables/tables/tests/test_direct_chunk.py", line 255, in _test_write_chunk_missing
    new_obj.resize(self.array.shape)
ValueError: cannot resize an array with refcheck=True on PyPy.
Use the np.resize function or refcheck=False

======================================================================
ERROR: None (tables.tests.test_direct_chunk.TableDirectChunkingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/PyTables/tables/tests/test_direct_chunk.py", line 266, in test_write_chunk_missing1
    return self._test_write_chunk_missing(shrink_after=False)
  File "/tmp/PyTables/tables/tests/test_direct_chunk.py", line 255, in _test_write_chunk_missing
    new_obj.resize(self.array.shape)
ValueError: cannot resize an array with refcheck=True on PyPy.
Use the np.resize function or refcheck=False

======================================================================
ERROR: None (tables.tests.test_direct_chunk.TableDirectChunkingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/PyTables/tables/tests/test_direct_chunk.py", line 269, in test_write_chunk_missing2
    return self._test_write_chunk_missing(shrink_after=True)
  File "/tmp/PyTables/tables/tests/test_direct_chunk.py", line 255, in _test_write_chunk_missing
    new_obj.resize(self.array.shape)
ValueError: cannot resize an array with refcheck=True on PyPy.
Use the np.resize function or refcheck=False

----------------------------------------------------------------------
Ran 6852 tests in 1075.999s

FAILED (errors=4, skipped=14)
```

Note that I'm also getting a lot of (non-fatal), but I think they were present earlier too:

```pytb
Exception ignored in: <function Node.__del__ at 0x00007fd8f41348e0>
Traceback (most recent call last):
  File "/tmp/PyTables/tables/node.py", line 302, in __del__
    node_manager = self._v_file._node_manager
AttributeError: 'File' object has no attribute '_node_manager'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/PyTables/tables/node.py", line 310, in __del__
    self._f_close()
  File "/tmp/PyTables/tables/table.py", line 3045, in _f_close
    self.flush()
  File "/tmp/PyTables/tables/table.py", line 2976, in flush
    if self._v_file._iswritable():
  File "/tmp/PyTables/tables/file.py", line 2183, in _iswritable
    return self.mode in ('w', 'a', 'r+')
AttributeError: 'File' object has no attribute 'mode'
```

**Comment by avalentino** [comment]
@mgorny thanks for reporting
Unfortunately we do not have a PyPy CI pipeline.
Can I kindly ask you if using `np.resize` instead of `new_obj.resize` actually solves the issue?

Regarding "(non-fatal)", I understand that they are linked to the PyPy execution as well, right?
Could I kindly ask you to report them in a dedicated issue?

**Comment by mgorny** [comment]
> @mgorny thanks for reporting Unfortunately we do not have a PyPy CI pipeline. Can I kindly ask you if using `np.resize` instead of `new_obj.resize` actually solves the issue?

I'm afraid only partially. I've used the following change (as `np.resize()` doesn't resize in place):

```diff
diff --git a/tables/tests/test_direct_chunk.py b/tables/tests/test_direct_chunk.py
index ccc82516..e4b73217 100644
--- a/tables/tests/test_direct_chunk.py
+++ b/tables/tests/test_direct_chunk.py
@@ -251,8 +251,7 @@ class XDirectChunkingTestCase(DirectChunkingTestCase):
             self.array.truncate(self.shape[0] + 1)
             self.array.truncate(self.shape[0] - 1)
 
-        new_obj = self.obj.copy()
-        new_obj.resize(self.array.shape)
+        new_obj = np.resize(self.obj, self.array.shape)
         obj_slice = tuple(slice(s, s + cs) for (s, cs)
                           in zip(chunk_start, self.chunkshape))
         if not shrink_after:
```

Now it's down to two failures:

```pytb
======================================================================
FAIL: None (__main__.EArrayDirectChunkingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/PyTables/tables/tests/test_direct_chunk.py", line 265, in test_write_chunk_missing1
    return self._test_write_chunk_missing(shrink_after=False)
  File "/tmp/PyTables/tables/tests/test_direct_chunk.py", line 262, in _test_write_chunk_missing
    self.assertTrue(common.areArraysEqual(self.array[:], new_obj))
AssertionError: False is not true

======================================================================
FAIL: None (__main__.TableDirectChunkingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/PyTables/tables/tests/test_direct_chunk.py", line 265, in test_write_chunk_missing1
    return self._test_write_chunk_missing(shrink_after=False)
  File "/tmp/PyTables/tables/tests/test_direct_chunk.py", line 262, in _test_write_chunk_missing
    self.assertTrue(common.areArraysEqual(self.array[:], new_obj))
AssertionError: False is not true
```

I suppose it's because:

> Note that this behavior is different from a.resize(new_shape) which fills with zeros instead of repeated copies of a. ([numpy.resize](https://numpy.org/doc/stable/reference/generated/numpy.resize.html))
 
> Regarding "(non-fatal)", I understand that they are linked to the PyPy execution as well, right? Could I kindly ask you to report them in a dedicated issue?

Sure, will do.

**Comment by mgorny** [comment]
Hmm, the doc for `refcheck` arg says:

> The purpose of the reference count check is to make sure you do not use this array as a buffer for another Python object and then reallocate the memory. However, reference counts can increase in other ways so if you are sure that you have not shared the memory for this array with another Python object, then you may safely set refcheck to False.
> [numpy.ndarray.resize](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.resize.html)

So perhaps it'd be simpler to use `refcheck=False`, given that the object was just copied.

**Comment by avalentino** [comment]
Well, I guess that it is safe to use `refcheck=False` just after a `new_obj = self.obj.copy()`

**Comment by mgorny** [comment]
Do you want me to make a pull request?

**Comment by avalentino** [comment]
It would be really appreciated, thanks
The fix for this issue will go in the hotfix release that we are going to prepare.
