### ISSUE TITLE
Error when using pttree with unlimited max depth

### ISSUE THREAD

**Issue by mdebony** [PyTables/PyTables#1224]
Hello,

I was inspecting a files using the pttree tools. When I tried to set the maximum depth to unlimited using this command :
`pttree -L -1 my_file.h5`

I got this error message :
```Traceback (most recent call last):
  File "/home/mathieu.debony/workspace/software/mambaforge/envs/lst-analysis/bin/pttree", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/fefs/aswg/workspace/mathieu.debony/software/mambaforge/envs/lst-analysis/lib/python3.11/site-packages/tables/scripts/pttree.py", line 103, in main
    tree_str = get_tree_str(f, nodename, **args.__dict__)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fefs/aswg/workspace/mathieu.debony/software/mambaforge/envs/lst-analysis/lib/python3.11/site-packages/tables/scripts/pttree.py", line 122, in get_tree_str
    max_depth = os.sys.maxint
                ^^^^^^^^^^^^^
AttributeError: module 'sys' has no attribute 'maxint'
```

I'm using pytables 3.10.1 installed through conda forge package (py311h6d53d72_4). I'm using it within a python 3.11 environment.

Let me know if I could provide you any other useful information.

**Comment by avalentino** [comment]
Hi @mdebony 
Thanks for reporting
Should be fixed now
