### ISSUE TITLE
Installation of package can occasionally fail if Cython is not installed

### ISSUE THREAD

**Issue by cviner** [PyTables/PyTables#465]
Installation of PyTables via: ```pip install tables``` can fail with the following error: 

```
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-aFpNcC/tables/setup.py", line 671, in <module>
        cython_extfiles = get_cython_extfiles(cython_extnames)
      File "/tmp/pip-build-aFpNcC/tables/setup.py", line 664, in get_cython_extfiles
        from Cython.Build import cythonize
    ImportError: No module named Cython.Build
```

This only occurs rarely, in a time-dependent fashion, and appears to be do to: ```newer(extpfile, extcfile)```, on [line 660 of setup.py](https://github.com/PyTables/PyTables/blob/develop/setup.py#L660).

**Comment by andreabedini** [comment]
Hi @cviner, thanks for reporting this.

Perhaps that mechanism is a bit fragile, we will review that at some point.

The workaround is to install cython before installing pytables.
