### ISSUE TITLE
installation problem: some tests fail 

### ISSUE THREAD

**Issue by ziggi0703** [PyTables/PyTables#482]
during the installation of PyTables I had 4 tests which have failed. Here ist the full output of tables.test():

```python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tables
>>> tables.test()
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.2.0.dev0
HDF5 version:        1.8.11
NumPy version:       1.9.2
Numexpr version:     2.4.3 (not using Intel's VML/MKL)
Zlib version:        1.2.8 (in Python interpreter)
BZIP2 version:       1.0.6 (6-Sept-2010)
Blosc version:       1.4.4 (2015-05-05)
Blosc compressors:   blosclz (1.0.2.1), lz4 (1.2.0), lz4hc (1.2.0), snappy (1.1.1), zlib (1.2.8)
Cython version:      0.23
Python version:      2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
Platform:            Linux-3.13.0-61-generic-x86_64-with-Ubuntu-14.04-trusty
Byte-ordering:       little
Detected cores:      8
Default encoding:    ascii
Default FS encoding: UTF-8
Default locale:      (en_US, UTF-8)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Performing only a light (yet comprehensive) subset of the test suite.
If you want a more complete test, try passing the --heavy flag to this script
(or set the 'heavy' parameter in case you are using tables.test() call).
The whole suite will take more than 4 hours to complete on a relatively
modern CPU and around 512 MB of main memory.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
tables/filters.py:292: FiltersWarning: compression library ``lzo`` is not available; using ``zlib`` instead
  % (complib, default_complib), FiltersWarning)
.tables/path.py:110: NaturalNameWarning: object name is not a valid Python identifier: 'a:b'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
tables/path.py:110: NaturalNameWarning: object name is not a valid Python identifier: '/a/b'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
tables/path.py:110: NaturalNameWarning: object name is not a valid Python identifier: '.'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................sssss..................................................................................................................................................................................................................................................................................................................................................................................................................................................................ssssssssssssssssssssssssssssssssssssssssssssssssss........................................................................................................................................................................E...............E....................................................................................................................................................................................................................................................................................................................................................E..............E..........................................................................................................................ssssss...................................................................................................................................................................................................................................................................................................................................................................................................................................................sssssss........................................................ssssssssssssss...................................................................................................................................................................................................ssssssssss.................................................................ssssssssss.................................................................sssss...............sssss..........................................................................................................................................................................ssssss..............................................................................................................................................................................................................s..........................................................................................................................................................................................................................................................................................s...s................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................ssssssssssssssssssss..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
======================================================================
ERROR: None (tables.tests.test_tables.RecArrayRangeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tables/tests/test_tables.py", line 2169, in test01a_range
    self.check_range()
  File "tables/tests/test_tables.py", line 2042, in check_range
    recarray = table.read(self.start, self.stop, self.step)
  File "tables/table.py", line 1921, in read
    arr = self._read(start, stop, step, field, out)
  File "tables/table.py", line 1843, in _read
    self.row._fill_col(result, start, stop, step, field)
  File "tables/tableextension.pyx", line 1258, in tables.tableextension.Row._fill_col (tables/tableextension.c:14946)
    result[startr:stopr] = fields[istartb::istep]
ValueError: could not broadcast input array from shape (2) into shape (0)

======================================================================
ERROR: None (tables.tests.test_tables.GetColRangeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tables/tests/test_tables.py", line 2169, in test01a_range
    self.check_range()
  File "tables/tests/test_tables.py", line 2050, in check_range
    column = table.read(self.start, self.stop, self.step, 'var2')
  File "tables/table.py", line 1921, in read
    arr = self._read(start, stop, step, field, out)
  File "tables/table.py", line 1843, in _read
    self.row._fill_col(result, start, stop, step, field)
  File "tables/tableextension.pyx", line 1258, in tables.tableextension.Row._fill_col (tables/tableextension.c:14946)
    result[startr:stopr] = fields[istartb::istep]
ValueError: could not broadcast input array from shape (2) into shape (0)

======================================================================
ERROR: None (tables.tests.test_tablesMD.RecArrayRangeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tables/tests/test_tablesMD.py", line 746, in test01a_range
    self.check_range()
  File "tables/tests/test_tablesMD.py", line 620, in check_range
    recarray = table.read(self.start, self.stop, self.step)
  File "tables/table.py", line 1921, in read
    arr = self._read(start, stop, step, field, out)
  File "tables/table.py", line 1843, in _read
    self.row._fill_col(result, start, stop, step, field)
  File "tables/tableextension.pyx", line 1258, in tables.tableextension.Row._fill_col (tables/tableextension.c:14946)
    result[startr:stopr] = fields[istartb::istep]
ValueError: could not broadcast input array from shape (2) into shape (0)

======================================================================
ERROR: None (tables.tests.test_tablesMD.GetColRangeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tables/tests/test_tablesMD.py", line 746, in test01a_range
    self.check_range()
  File "tables/tests/test_tablesMD.py", line 629, in check_range
    column = table.read(self.start, self.stop, self.step, 'var2')
  File "tables/table.py", line 1921, in read
    arr = self._read(start, stop, step, field, out)
  File "tables/table.py", line 1843, in _read
    self.row._fill_col(result, start, stop, step, field)
  File "tables/tableextension.pyx", line 1258, in tables.tableextension.Row._fill_col (tables/tableextension.c:14946)
    result[startr:stopr] = fields[istartb::istep]
ValueError: could not broadcast input array from shape (2,2,2) into shape (0,2,2)

----------------------------------------------------------------------
Ran 5741 tests in 95.890s

FAILED (errors=4, skipped=141)
1
```

Do you know what's going wrong?

**Comment by scopatz** [comment]
Hmm this seems like it could be a numpy issue.  Those shapes seem broadcastable.

**Comment by andreabedini** [comment]
yes, it's #481. Closing as duplicate.

**Comment by andreabedini** [comment]
@ziggi0703 To work around this either use a version of cython earlier than 0.23 or use the PyTables release 3.2.1 that ships with cython files already compiled with c-extensions. If you have time please help debug #481.

**Comment by ziggi0703** [comment]
thanks for your fast replies

**Comment by andreabedini** [comment]
@ziggi0703 no problem, let me know how it goes
