### ISSUE TITLE
Some tests require UTF-8 locale

### ISSUE THREAD

**Issue by warsaw** [PyTables/PyTables#485]
When we build PyTables for Ubuntu, the build machines by definition use a C/POSIX locale.  This breaks the following tests, all of which error with UnicodeEncodeErrors:

ERROR: test01 (tables.tests.test_basics.UnicodeFilename)
Checking creating a filename with Unicode chars.

ERROR: test02 (tables.tests.test_basics.UnicodeFilename)
Checking  tables.is_hdf5_file with a Unicode filename.

ERROR: test03 (tables.tests.test_basics.UnicodeFilename)
Checking is_pytables_file with a Unicode filename.

ERROR: test_store_and_load_with_non_ascii_attributes (tables.tests.test_basics.UnicodeFilename)

Forcing the test suite to run under say en_US.UTF-8 allows the tests to pass.

**Comment by scopatz** [comment]
Which version of Ubuntu is this for? What version of Python, etc?  Can you post the full test output, please?

**Comment by avalentino** [comment]
Hi @scopatz, I can confirm the issue on debian Sid

```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.2.0rc3
HDF5 version:        1.8.13
NumPy version:       1.9.2
Numexpr version:     2.4 (not using Intel's VML/MKL)
Zlib version:        1.2.8 (in Python interpreter)
LZO version:         2.08 (Jun 29 2014)
BZIP2 version:       1.0.6 (6-Sept-2010)
Blosc version:       1.4.4 (2015-05-05)
Blosc compressors:   blosclz (1.0.2.1), lz4 (1.7.0), lz4hc (1.7.0), snappy (unknown), zlib (1.2.8)
Cython version:      0.22.1
Python version:      2.7.10 (default, Jul  1 2015, 10:54:53) 
[GCC 4.9.2]
Platform:            Linux-3.19.0-26-generic-x86_64-with-debian-stretch-sid
Byte-ordering:       little
Detected cores:      4
Default encoding:    ascii
Default FS encoding: ANSI_X3.4-1968
Default locale:      (None, None)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

[CUT]

======================================================================
ERROR: test01 (tables.tests.test_basics.UnicodeFilename)
Checking creating a filename with Unicode chars.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pytables-3.2.0/build/lib.linux-x86_64-2.7/tables/tests/test_basics.py", line 1930, in setUp
    super(UnicodeFilename, self).setUp()
  File "/home/antonio/debian/git/build-area/pytables-3.2.0/build/lib.linux-x86_64-2.7/tables/tests/common.py", line 422, in setUp
    self.h5fname = self._getTempFileName()
  File "/home/antonio/debian/git/build-area/pytables-3.2.0/build/lib.linux-x86_64-2.7/tables/tests/test_basics.py", line 1927, in _getTempFileName
    return tempfile.mktemp(prefix=self.unicode_prefix, suffix='.h5')
  File "/usr/lib/python2.7/tempfile.py", line 366, in mktemp
    if not _exists(file):
  File "/usr/lib/python2.7/tempfile.py", line 102, in _exists
    _stat(fn)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0140' in position 9: ordinal not in range(128)

======================================================================
ERROR: test02 (tables.tests.test_basics.UnicodeFilename)
Checking  tables.is_hdf5_file with a Unicode filename.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pytables-3.2.0/build/lib.linux-x86_64-2.7/tables/tests/test_basics.py", line 1930, in setUp
    super(UnicodeFilename, self).setUp()
  File "/home/antonio/debian/git/build-area/pytables-3.2.0/build/lib.linux-x86_64-2.7/tables/tests/common.py", line 422, in setUp
    self.h5fname = self._getTempFileName()
  File "/home/antonio/debian/git/build-area/pytables-3.2.0/build/lib.linux-x86_64-2.7/tables/tests/test_basics.py", line 1927, in _getTempFileName
    return tempfile.mktemp(prefix=self.unicode_prefix, suffix='.h5')
  File "/usr/lib/python2.7/tempfile.py", line 366, in mktemp
    if not _exists(file):
  File "/usr/lib/python2.7/tempfile.py", line 102, in _exists
    _stat(fn)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0140' in position 9: ordinal not in range(128)

======================================================================
ERROR: test03 (tables.tests.test_basics.UnicodeFilename)
Checking is_pytables_file with a Unicode filename.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pytables-3.2.0/build/lib.linux-x86_64-2.7/tables/tests/test_basics.py", line 1930, in setUp
    super(UnicodeFilename, self).setUp()
  File "/home/antonio/debian/git/build-area/pytables-3.2.0/build/lib.linux-x86_64-2.7/tables/tests/common.py", line 422, in setUp
    self.h5fname = self._getTempFileName()
  File "/home/antonio/debian/git/build-area/pytables-3.2.0/build/lib.linux-x86_64-2.7/tables/tests/test_basics.py", line 1927, in _getTempFileName
    return tempfile.mktemp(prefix=self.unicode_prefix, suffix='.h5')
  File "/usr/lib/python2.7/tempfile.py", line 366, in mktemp
    if not _exists(file):
  File "/usr/lib/python2.7/tempfile.py", line 102, in _exists
    _stat(fn)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0140' in position 9: ordinal not in range(128)

======================================================================
ERROR: test_store_and_load_with_non_ascii_attributes (tables.tests.test_basics.UnicodeFilename)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/pytables-3.2.0/build/lib.linux-x86_64-2.7/tables/tests/test_basics.py", line 1930, in setUp
    super(UnicodeFilename, self).setUp()
  File "/home/antonio/debian/git/build-area/pytables-3.2.0/build/lib.linux-x86_64-2.7/tables/tests/common.py", line 422, in setUp
    self.h5fname = self._getTempFileName()
  File "/home/antonio/debian/git/build-area/pytables-3.2.0/build/lib.linux-x86_64-2.7/tables/tests/test_basics.py", line 1927, in _getTempFileName
    return tempfile.mktemp(prefix=self.unicode_prefix, suffix='.h5')
  File "/usr/lib/python2.7/tempfile.py", line 366, in mktemp
    if not _exists(file):
  File "/usr/lib/python2.7/tempfile.py", line 102, in _exists
    _stat(fn)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0140' in position 9: ordinal not in range(128)

----------------------------------------------------------------------
Ran 5734 tests in 216.714s

FAILED (errors=4, skipped=14)
```

**Comment by warsaw** [comment]
Yep, those are exactly the errors I saw.  FWIW, I added the following to debian/rules in the Ubuntu version (also attached to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=795333)

```
	mkdir -p $(CURDIR)/tmp-locales
	localedef -i /usr/share/i18n/locales/en_US -c -f UTF-8 \
		-A /usr/share/locale/locale.alias \
		$(CURDIR)/tmp-locales/en_US.UTF-8
	set -e -x; \
	for py in $(PY2VERS); do \
		cd $(CURDIR)/build/lib.*-$$py; \
		env PYTHONPATH=. \
		    LOCPATH=$(CURDIR)/tmp-locales LC_ALL=en_US.UTF-8 \
		    python$$py tables/tests/test_all.py -vvv; \
		cd $(CURDIR)/debian/tmp/usr/lib/python$$py/dist-packages; \
		env PYTHONPATH=. \
		    LOCPATH=$(CURDIR)/tmp-locales LC_ALL=en_US.UTF-8 \
		    python$$py-dbg tables/tests/test_all.py -vvv; \
	done
	set -e -x; \
	for py in $(PY3VERS); do \
		cd $(CURDIR)/build/lib.*-$$py; \
		env PYTHONPATH=. \
		    LOCPATH=$(CURDIR)/tmp-locales LC_ALL=en_US.UTF-8 \
		    python$$py tables/tests/test_all.py -vvv; \
		#cd $(CURDIR)/debian/tmp/usr/lib/python3/dist-packages; \
		#env PYTHONPATH=. python$$py-dbg tables/tests/test_all.py -vvv; \
	done
```
