### ISSUE TITLE
can't install latest master under python 2.7

### ISSUE THREAD

**Issue by dx-pbuckley** [PyTables/PyTables#502]
On CentOS release 6.7 I can no longer `pip install -e git+git://github.com/PyTables/PyTables.git#egg=PyTables`. I get the error output listed at the end of this comment. I've confirmed that https://github.com/PyTables/PyTables/pull/493 is when it broke (I can `pip install -e git+git://github.com/PyTables/PyTables.git@50e9ebf9c9ba5648995f0c95cc7991a97584f42c#egg=PyTables` successfully).

```
     [root@ye-olde-obscure-hostname ~]# pip install -e git+git://github.com/PyTables/PyTables.git#egg=PyTables
Obtaining PyTables from git+git://github.com/PyTables/PyTables.git#egg=PyTables
  Cloning git://github.com/PyTables/PyTables.git to ./src/pytables
    Complete output from command python setup.py egg_info:
    /usr/bin/ld: cannot find -llzo2
    collect2: ld returned 1 exit status
    /usr/bin/ld: cannot find -llzo
    collect2: ld returned 1 exit status
    /usr/bin/ld: cannot find -lblosc
    collect2: ld returned 1 exit status
    warning: tables/utilsextension.pyx:796:12: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    warning: tables/utilsextension.pyx:796:22: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        values = enum_atom._values
    
        # This saves the default enum value first so that we can restore it
        default_name = enum_atom._defname
        index_default = names.index(default_name)
        H5Tenum_insert(enum_id, default_name.encode('utf-8'),
                                                  ^
    ------------------------------------------------------------
    
    tables/utilsextension.pyx:1128:47: Obtaining 'char *' from temporary Python value
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        for i, n in enumerate(names):
          # Skip the default value as we have already inserted it before
          if i == index_default:
            continue
    
          if H5Tenum_insert(enum_id, n.encode('utf-8'),
                                            ^
    ------------------------------------------------------------
    
    tables/utilsextension.pyx:1136:41: Obtaining 'char *' from temporary Python value
    * Using Python 2.7.6 (default, Sep 15 2015, 01:19:35)
    * USE_PKGCONFIG: True
    * Found HDF5 headers at ``/usr/include``, library at ``/usr/lib64``.
    * Could not find LZO 2 headers and library; disabling support for it.
    * Could not find LZO 1 headers and library; disabling support for it.
    * Found bzip2 headers at ``/usr/include``, library at ``/usr/lib64``.
    * Could not find blosc headers and library; using internal sources.
    Compiling tables/utilsextension.pyx because it changed.
    Cythonizing tables/utilsextension.pyx
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/root/src/pytables/setup.py", line 648, in <module>
        cython_extfiles = get_cython_extfiles(cython_extnames)
      File "/root/src/pytables/setup.py", line 642, in get_cython_extfiles
        cythonize(extpfile)
      File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 785, in cythonize
        cythonize_one(*args[1:])
      File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 902, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: tables/utilsextension.pyx
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /root/src/pytables
```

**Comment by andreabedini** [comment]
Thanks for the report @dx-pbuckley. Cython seems to raise an honest complaint there but I don't understand why neither travis or I got that error. What version of Cython are you using?

**Comment by andreabedini** [comment]
it seems Cython supports passing pointers to temporary python objects inside function calls as of [version 0.21](https://github.com/cython/cython/blob/master/CHANGES.rst#021-2014-09-10). Please upgrade Cython.

**Comment by dx-pbuckley** [comment]
thanks @andreabedini, I confirmed that upgrading cython to 0.21 fixed the issue compiling latest master
