### ISSUE TITLE
NoSuchNodeError in tables.tests.test_basics.CheckFileTestCase (Python 3.5)

### ISSUE THREAD

**Issue by groutr** [PyTables/PyTables#513]
With Python 3.5, I get the following error when running the PyTables 3.2.2 test suite on Windows 10.  The test suite run with Python 2.7 and Python 3.4 pass without errors.  
```
======================================================================
ERROR: None (tables.tests.test_basics.CheckFileTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\aroot\stage\lib\site-packages\tables\tests\test_basics.py", line 1288, in test04_openGenericHDF5File
    array_ = h5file.get_node(columns, "TDC", classname="Array")
  File "C:\aroot\stage\lib\site-packages\tables\file.py", line 1616, in get_node
    node = self._get_node(nodepath)
  File "C:\aroot\stage\lib\site-packages\tables\file.py", line 1555, in _get_node
    node = self._node_manager.get_node(nodepath)
  File "C:\aroot\stage\lib\site-packages\tables\file.py", line 436, in get_node
    node = self.node_factory(key)
  File "C:\aroot\stage\lib\site-packages\tables\group.py", line 1186, in _g_load_child
    node_type = self._g_check_has_child(childname)
  File "C:\aroot\stage\lib\site-packages\tables\group.py", line 402, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``/columns/TDC``

----------------------------------------------------------------------
Ran 5738 tests in 445.550s

FAILED (errors=1, skipped=236)
```
Can someone reproduce this?

**Comment by avalentino** [comment]
Warnings should be fixed in 6d0a5a3f
