### ISSUE TITLE
libref in 3.3.0 docs broken

### ISSUE THREAD

**Issue by tomkooij** [PyTables/PyTables#572]
The libref in the userguide was broken in the online docs. Reported on gitter by @moritz-lotze

I reverted the 3.3.0 documentation commit in PyTables/pytables.github.com. The 3.2.3 docs are back online now. I'll try to look into it when I have time.

**Comment by tomkooij** [comment]
The error is due to autodoc being broken in `doc/source/userguide/libref/`:

many failures similar to:
```
(...)PyTables/doc/source/usersguide/libref/declarative_classes.rst:54: WARNING: autodoc: failed to import class u'StringAtom' from module u'tables'; the following exception was raised:
Traceback (most recent call last):
  File "(...)/site-packages/Sphinx-1.4.1-py2.7.egg/sphinx/ext/autodoc.py", line 507, in import_object
    __import__(self.modname)
  File "/data/hisparc/tom/PyTables/tables/__init__.py", line 90, in <module>
    from .utilsextension import (
ImportError: No module named utilsextension
```

This is the python 2.7 version of sphinx-build. The python3 version won't run because of our extensions. (That we should probably `py2to3` but that's for another issue)

**Comment by tomkooij** [comment]
Solved:

The current version of pytables was not **installed** in the environment used to build the docs.

```
$ python setup.py develop  # or install
$ make dist   # or cd doc && make html
```

docs updated and pushed to pytabels.github.io
