### ISSUE TITLE
Test failure on bigendian architectures

### ISSUE THREAD

**Issue by avalentino** [PyTables/PyTables#583]
It seems that PyTables v3.3.0 + HDF5 v1.10 patch has some problem on bigendian machines (e.g. mips and s390x).
The relevant part of the test log is reported below and seems to indicate some issue with the blosc bitshuffle filter. The full log can be found at [1].

Please note that the debian package for PyTables v3.3.0 has been built against the system blosc v1.11.1.
The issue was not present in PyTabòles v3.2.2 with blosc 1.4.4 (no bitshuffle filter if I remember well).

Any idea about the possible problem/solution?
Is there any incompatibility with latest blosc versions that I'm not aware?
 
[1] https://buildd.debian.org/status/package.php?p=pytables

```
======================================================================
ERROR: None (tables.tests.test_vlarray.BloscBitShuffleComprTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/tables/tests/test_vlarray.py", line 92, in test01_read
    row = vlarray.read(0)[0]
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/tables/vlarray.py", line 811, in read
    listarr = self._read_array(start, stop, step)
  File "tables/hdf5extension.pyx", line 2083, in tables.hdf5extension.VLArray._read_array (tables/hdf5extension.c:22941)
HDF5ExtError: HDF5 error back trace

  File "../../../src/H5Dio.c", line 173, in H5Dread
    can't read data
  File "../../../src/H5Dio.c", line 551, in H5D__read
    can't read data
  File "../../../src/H5Dchunk.c", line 1904, in H5D__chunk_read
    chunked read failed
  File "../../../src/H5Dscatgath.c", line 542, in H5D__scatgath_read
    datatype conversion failed
  File "../../../src/H5T.c", line 4832, in H5T_convert
    data type conversion failed
  File "../../../src/H5Tconv.c", line 3274, in H5T__conv_vlen
    can't read VL data
  File "../../../src/H5Tvlen.c", line 891, in H5T_vlen_disk_read
    Unable to read VL information
  File "../../../src/H5HG.c", line 622, in H5HG_read
    unable to protect global heap
  File "../../../src/H5HG.c", line 262, in H5HG_protect
    unable to protect global heap
  File "../../../src/H5AC.c", line 1262, in H5AC_protect
    H5C_protect() failed.
  File "../../../src/H5C.c", line 3574, in H5C_protect
    can't load entry
  File "../../../src/H5C.c", line 7954, in H5C_load_entry
    unable to load entry
  File "../../../src/H5HGcache.c", line 136, in H5HG_load
    unable to read global heap collection
  File "../../../src/H5Fio.c", line 120, in H5F_block_read
    read through metadata accumulator failed
  File "../../../src/H5Faccum.c", line 263, in H5F__accum_read
    driver read request failed
  File "../../../src/H5FDint.c", line 207, in H5FD_read
    addr overflow, addr = 61458, size=4096, eoa=9332

End of HDF5 error back trace

VLArray._read_array: Problems reading the array data.

======================================================================
ERROR: None (tables.tests.test_vlarray.BloscBitShuffleComprTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/tables/tests/test_vlarray.py", line 154, in test02a_getitem
    rows2 = vlarray[slc]
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/tables/vlarray.py", line 675, in __getitem__
    return self.read(start, stop, step)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/tables/vlarray.py", line 811, in read
    listarr = self._read_array(start, stop, step)
  File "tables/hdf5extension.pyx", line 2083, in tables.hdf5extension.VLArray._read_array (tables/hdf5extension.c:22941)
HDF5ExtError: HDF5 error back trace

  File "../../../src/H5Dio.c", line 173, in H5Dread
    can't read data
  File "../../../src/H5Dio.c", line 551, in H5D__read
    can't read data
  File "../../../src/H5Dchunk.c", line 1904, in H5D__chunk_read
    chunked read failed
  File "../../../src/H5Dscatgath.c", line 542, in H5D__scatgath_read
    datatype conversion failed
  File "../../../src/H5T.c", line 4832, in H5T_convert
    data type conversion failed
  File "../../../src/H5Tconv.c", line 3274, in H5T__conv_vlen
    can't read VL data
  File "../../../src/H5Tvlen.c", line 891, in H5T_vlen_disk_read
    Unable to read VL information
  File "../../../src/H5HG.c", line 622, in H5HG_read
    unable to protect global heap
  File "../../../src/H5HG.c", line 262, in H5HG_protect
    unable to protect global heap
  File "../../../src/H5AC.c", line 1262, in H5AC_protect
    H5C_protect() failed.
  File "../../../src/H5C.c", line 3574, in H5C_protect
    can't load entry
  File "../../../src/H5C.c", line 7954, in H5C_load_entry
    unable to load entry
  File "../../../src/H5HGcache.c", line 136, in H5HG_load
    unable to read global heap collection
  File "../../../src/H5Fio.c", line 120, in H5F_block_read
    read through metadata accumulator failed
  File "../../../src/H5Faccum.c", line 263, in H5F__accum_read
    driver read request failed
  File "../../../src/H5FDint.c", line 207, in H5FD_read
    addr overflow, addr = 61458, size=4096, eoa=9332

End of HDF5 error back trace

VLArray._read_array: Problems reading the array data.

======================================================================
ERROR: None (tables.tests.test_vlarray.BloscBitShuffleComprTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/tables/tests/test_vlarray.py", line 187, in test02b_getitem
    rows = numpy.array(vlarray[:], dtype=numpy.object)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/tables/vlarray.py", line 675, in __getitem__
    return self.read(start, stop, step)
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/tables/vlarray.py", line 811, in read
    listarr = self._read_array(start, stop, step)
  File "tables/hdf5extension.pyx", line 2083, in tables.hdf5extension.VLArray._read_array (tables/hdf5extension.c:22941)
HDF5ExtError: HDF5 error back trace

  File "../../../src/H5Dio.c", line 173, in H5Dread
    can't read data
  File "../../../src/H5Dio.c", line 551, in H5D__read
    can't read data
  File "../../../src/H5Dchunk.c", line 1904, in H5D__chunk_read
    chunked read failed
  File "../../../src/H5Dscatgath.c", line 542, in H5D__scatgath_read
    datatype conversion failed
  File "../../../src/H5T.c", line 4832, in H5T_convert
    data type conversion failed
  File "../../../src/H5Tconv.c", line 3274, in H5T__conv_vlen
    can't read VL data
  File "../../../src/H5Tvlen.c", line 891, in H5T_vlen_disk_read
    Unable to read VL information
  File "../../../src/H5HG.c", line 622, in H5HG_read
    unable to protect global heap
  File "../../../src/H5HG.c", line 262, in H5HG_protect
    unable to protect global heap
  File "../../../src/H5AC.c", line 1262, in H5AC_protect
    H5C_protect() failed.
  File "../../../src/H5C.c", line 3574, in H5C_protect
    can't load entry
  File "../../../src/H5C.c", line 7954, in H5C_load_entry
    unable to load entry
  File "../../../src/H5HGcache.c", line 136, in H5HG_load
    unable to read global heap collection
  File "../../../src/H5Fio.c", line 120, in H5F_block_read
    read through metadata accumulator failed
  File "../../../src/H5Faccum.c", line 263, in H5F__accum_read
    driver read request failed
  File "../../../src/H5FDint.c", line 207, in H5FD_read
    addr overflow, addr = 61458, size=4096, eoa=9332

End of HDF5 error back trace

VLArray._read_array: Problems reading the array data.

======================================================================
FAIL: None (tables.tests.test_carray.BloscBitShuffleTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/tables/tests/test_carray.py", line 180, in test01_readCArray
    self.assertTrue(allequal(data, obj, self.flavor))
AssertionError: False is not true

======================================================================
FAIL: None (tables.tests.test_carray.BloscBitShuffleTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/tables/tests/test_carray.py", line 239, in test01_readCArray_out_argument
    self.assertTrue(allequal(data, obj, self.flavor))
AssertionError: False is not true

======================================================================
FAIL: None (tables.tests.test_carray.BloscBitShuffleTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/tables/tests/test_carray.py", line 300, in test02_getitemCArray
    self.assertTrue(allequal(data, obj, self.flavor))
AssertionError: False is not true

======================================================================
FAIL: None (tables.tests.test_carray.BloscBitShuffleTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/tables/tests/test_carray.py", line 379, in test03_setitemCArray
    self.assertTrue(allequal(data, obj, self.flavor))
AssertionError: False is not true

======================================================================
FAIL: None (tables.tests.test_vlarray.BloscBitShuffleComprTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/tables/tests/test_vlarray.py", line 234, in test03_append
    self.flavor))
AssertionError: 0 is not true

======================================================================
FAIL: None (tables.tests.test_vlarray.BloscBitShuffleComprTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/build/lib.linux-mips-2.7/tables/tests/test_vlarray.py", line 252, in test04_get_row_size
    self.assertEqual(vlarray.get_row_size(0), 2 * vlarray.atom.size)
AssertionError: 0L != 8

----------------------------------------------------------------------
Ran 6173 tests in 1961.711s

FAILED (failures=6, errors=3, skipped=28)
```

**Comment by FrancescAlted** [comment]
Yeah, it smells like there could be a problem with the [generic implementation of the bitshuffle filter in C-Blosc](https://github.com/Blosc/c-blosc/blob/master/blosc/bitshuffle-generic.c) (the accelerated SSE2 and AVX2 implementations cannot possibly be used in MIPS or S390x).  I'll open a ticket there, although not sure how long it would take to fix that (specially having in account the lack of big-endian platforms for testing).  Anyway, thanks to bringing this to our attention!

**Comment by opoplawski** [comment]
Same in Fedora - https://bugzilla.redhat.com/show_bug.cgi?id=1379123

**Comment by FrancescAlted** [comment]
Next release of PyTables should have PR #608 merged in, so this should be fixed.  I am closing this, but in case there are some glitches left, please feel free to reopen.
