### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by fl329** [PyTables/PyTables#619]
I'm using Ubuntu 14.04.5 LTS, and my python version is Python 2.7.6. 
I installed PyTables using pip, but when I tried to import it, I got this message: 
>>> import tables
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tables/__init__.py", line 90, in <module>
    from .utilsextension import (
  File "tables/utilsextension.pyx", line 26, in init tables.utilsextension (tables/utilsextension.c:20717)
  File "/usr/local/lib/python2.7/dist-packages/tables/description.py", line 25, in <module>
    from . import atom
  File "/usr/local/lib/python2.7/dist-packages/tables/atom.py", line 25, in <module>
    from .utils import SizeType
  File "/usr/local/lib/python2.7/dist-packages/tables/utils.py", line 25, in <module>
    from .flavor import array_of_flavor
  File "/usr/local/lib/python2.7/dist-packages/tables/flavor.py", line 54, in <module>
    from .exceptions import FlavorError, FlavorWarning
  File "/usr/local/lib/python2.7/dist-packages/tables/exceptions.py", line 26, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'

**Comment by tomkooij** [comment]
I cannot reproduce this on python 2.7.12 (Ubuntu 16 xenial)
What version of `six` are you using?

Can you try to upgrade six:
```
$ pip install -U six
$ python
>>> import tables
>>> import six
>>> six.__version__
'1.10.0'
```


My log:
```
Collecting tables
  Downloading tables-3.4.1-cp27-cp27mu-manylinux1_x86_64.whl (4.4MB)
    100% |████████████████████████████████| 4.4MB 132kB/s
Requirement already satisfied: numpy>=1.8.0 in ./miniconda/envs/py27/lib/python2.7/site-packages (from tables)
Requirement already satisfied: six in ./miniconda/envs/py27/lib/python2.7/site-packages (from tables)
Requirement already satisfied: numexpr>=2.5.2 in ./miniconda/envs/py27/lib/python2.7/site-packages (from tables)
Installing collected packages: tables
Successfully installed tables-3.4.1
(py27) tom@htpc:~$ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import tables

```

**Comment by tomkooij** [comment]
requirements six>=1.9.0 updated in 445a1d8d2a7f8dbb408c0f58c2ff9f45e2111877

**Comment by fl329** [comment]
It worked after upgrading six. Thanks!!

**Comment by tomkooij** [comment]
No problem. Thanks for reporting.
