### ISSUE TITLE
Error in test_array.PointSelection4 (numpy 1.13)

### ISSUE THREAD

**Issue by tomkooij** [PyTables/PyTables#637]
Appveyor CI tests fail on the wheelbuilder (tomkooij/pytables-wheels) at `test_array.PointSelection4`: [build on appveyor](https://ci.appveyor.com/project/tomkooij/pytables-wheels/build/job/gxnl89w5s17xf5c7)

Failures are random: It looks like (only 64bit builds?) fail random (but often). 
The build is against `numpy 1.13.0` so that might be the culprit.

```
======================================================================
FAIL: None (tables.tests.test_array.PointSelection4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda-x64\envs\test_env\lib\site-packages\tables\tests\test_array.py", line 2052, in test01a_read
    "NumPy array and PyTables selections does not match.")
AssertionError: NumPy array and PyTables selections does not match.
======================================================================
FAIL: None (tables.tests.test_array.PointSelection4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda-x64\envs\test_env\lib\site-packages\tables\tests\test_array.py", line 2119, in test02a_write
    "NumPy array and PyTables modifications does not match.")
AssertionError: NumPy array and PyTables modifications does not match.
----------------------------------------------------------------------````

```

**Comment by tomkooij** [comment]
It is indeed `numpy  `.13`. I can reproduce on my own system (using conda-forge hdf5 and numpy) but with self built pytables:
``` 
(py36) D:\pytables-wheels>python -m tables.tests.test_array
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.4.2-dev0
HDF5 version:        1.8.17
NumPy version:       1.13.0
Numexpr version:     2.6.2 (not using Intel's VML/MKL)
Zlib version:        1.2.11 (in Python interpreter)
Blosc version:       1.11.3 (2017-03-09)
Blosc compressors:   blosclz (1.0.5), lz4 (1.7.5), lz4hc (1.7.5), snappy (1.1.1), zlib (1.2.11), zstd (1.1.3)
Blosc filters:       shuffle, bitshuffle
Python version:      3.6.1 |Continuum Analytics, Inc.| (default, Mar 22 2017, 20:11:04) [MSC v.1900 64 bit (AMD64)]
Platform:            Windows-10-10.0.14393-SP0
Byte-ordering:       little
Detected cores:      4
Default encoding:    utf-8
Default FS encoding: utf-8
Default locale:      (nl_NL, cp1252)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
..................................................................................................................................................................................................................................................................................................................................................F..........................
======================================================================
FAIL: None (__main__.PointSelection4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\py36\lib\site-packages\tables\tests\test_array.py", line 2052, in test01a_read
    "NumPy array and PyTables selections does not match.")
AssertionError: False is not true : NumPy array and PyTables selections does not match.

----------------------------------------------------------------------
Ran 365 tests in 12.796s

FAILED (failures=1)
```

**Comment by cgohlke** [comment]
I can't reproduce the failure with numpy 1.13 (built from today's maintenance/1.13.x branch)
```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.4.2
HDF5 version:        1.10.1
NumPy version:       1.13.0
Numexpr version:     2.6.2 (using VML/MKL 2017.0.3)
Zlib version:        1.2.11 (in Python interpreter)
BZIP2 version:       1.0.6 (6-Sept-2010)
Blosc version:       1.11.3 (2017-03-09)
Blosc compressors:   blosclz (1.0.5), lz4 (1.7.1), lz4hc (1.7.1), snappy (unknown), zlib (1.2.11), zstd (1.1.3)
Blosc filters:       shuffle, bitshuffle
Cython version:      0.25.2
Python version:      3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
Platform:            Windows-10-10.0.15063-SP0
Byte-ordering:       little
Detected cores:      12
Default encoding:    utf-8
Default FS encoding: utf-8
Default locale:      (en_US, cp1252)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
.............................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 365 tests in 2.781s

OK
```

**Comment by tomkooij** [comment]
@cgohlke : Thanks for testing! 

I was wondering if this is the conda numpy, but: I can reproduce on my system with numpy, numexpr and pytables installed from wheels (i.e. not using the conda-forge numpy). As I use conda a lot, I cannot really rule out that this is still some conda thing, but:

I can reproduce also on CentOS using **Pytables 3.3.0** and numpy 1.13.



```
(npy113) D:\>pip install numpy==1.13
Collecting numpy==1.13
  Downloading numpy-1.13.0-cp36-none-win_amd64.whl (7.8MB)
    100% |████████████████████████████████| 7.8MB 73kB/s
Installing collected packages: numpy
Successfully installed numpy-1.13.0

(npy113) D:\>pip install tables
Collecting tables
  Downloading tables-3.4.2-cp36-cp36m-win_amd64.whl (2.5MB)
    100% |████████████████████████████████| 2.5MB 170kB/s
Requirement already satisfied: six>=1.9.0 in c:\miniconda3\envs\npy113\lib\site-packages (from tables)
Collecting numexpr>=2.5.2 (from tables)
  Using cached numexpr-2.6.2-cp36-none-win_amd64.whl
Requirement already satisfied: numpy>=1.8.0 in c:\miniconda3\envs\npy113\lib\site-packages (from tables)
Installing collected packages: numexpr, tables
Successfully installed numexpr-2.6.2 tables-3.4.2

(npy113) D:\>python -m tables.tests.test_array
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.4.2
HDF5 version:        1.8.17
NumPy version:       1.13.0
Numexpr version:     2.6.2 (not using Intel's VML/MKL)
Zlib version:        1.2.11 (in Python interpreter)
BZIP2 version:       1.0.6 (6-Sept-2010)
Blosc version:       1.11.3 (2017-03-09)
Blosc compressors:   blosclz (1.0.5), lz4 (1.7.5), lz4hc (1.7.5), snappy (1.1.1), zlib (1.2.8), zstd (1.1.3)
Blosc filters:       shuffle, bitshuffle
Python version:      3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:21:39) [MSC v.1900 64 bit (AMD64)]
Platform:            Windows-10-10.0.14393-SP0
Byte-ordering:       little
Detected cores:      4
Default encoding:    utf-8
Default FS encoding: utf-8
Default locale:      (nl_NL, cp1252)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
..................................................................................................................................................................................................................................................................................................................................................F..........................
======================================================================
FAIL: None (__main__.PointSelection4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\npy113\lib\site-packages\tables\tests\test_array.py", line 2052, in test01a_read
    "NumPy array and PyTables selections does not match.")
AssertionError: False is not true : NumPy array and PyTables selections does not match.

----------------------------------------------------------------------
Ran 365 tests in 9.551s

FAILED (failures=1)

```

**Comment by tomkooij** [comment]
I'm not sure what breaks, but it *sometimes* breaks:

```python
# simulate tables.tests.test_array.PointSelection4.test01a_read
import numpy as np
print(np.__version__)
shape = (1, 3, 2, 5, 6)  # Pointselection4
size = np.prod(shape)
nparr = np.arange(size, dtype=np.int32).reshape(shape)
key = (nparr >= 0) & (nparr < 10)
print(nparr[key])

import tables
#tables.print_versions()
for _ in range(10):
    with tables.open_file('discardme.h5', 'w') as f:
        f.create_array(f.root, 'array', nparr)
        print(f.root.array[key])

```
output:
```
(py36) D:\>python test_nparr.py
1.13.0
[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 0 0 0 0 0]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 0 0 0 0 0]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 0 0 0 0 0]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 0 0 0 0 0]
```
It should always output `[0 1 2 3 4 5 6 7 8 9]`

**Comment by cgohlke** [comment]
I can reproduce this with numpy-1.13.0, but not with numpy-1.13.x. So this might be fixed in numpy 1.13.1.

**Comment by tomkooij** [comment]
@cgohlke, thanks!

I tracked this down to: [_point_selection in leaf.py](https://github.com/PyTables/PyTables/blob/f97d9aeec2e2c22dccf0210caeecbe8b33a6e705/tables/leaf.py#L545)
`coords = numpy.asarray(key.nonzero(), dtype='i8')`

Which is probably a numpy bug, and already fixed, it seems.

**Comment by cgohlke** [comment]
`key.nonzero()` looks like https://github.com/numpy/numpy/issues/9304

**Comment by tomkooij** [comment]
Spot on @cgohlke ! That issue exactly matches the behaviour seen in the test above. And with your confirmation that 1.13.x fixes this, I'm closing this issue.

Thanks a lot!
