### ISSUE TITLE
Unicode group names in Python 2.7

### ISSUE THREAD

**Issue by gustavla** [PyTables/PyTables#652]
Although fine in Python 3, I have been having issues with opening HDF5 files with unicode group names under Python 2:

```python
# coding: utf-8
import tables

# Saving with unicode group names works and is compatible with other tools and Python 3
f = tables.open_file('test.h5', 'w')
f.create_group('/', u'é')
f.close()
```
Now, we can inspect this:
```
h5ls test.h5
\303\251                 Group
```
The group name got encoded using UTF-8: `'\303\251' == '\xc2\xa9' == u'é'.encode('utf-8')`.

Now, let's try to open this file:

```python
# coding: utf-8
import tables

f = tables.open_file('test.h5', 'r')
print f.root._v_children.keys()
# -> ['\xc3\xa9']
# So far no error, although we note that the string was not decoded 

print f.root._v_children[u'é'.encode('utf-8')]
# Error 1 (see below)

print f.root._v_children[u'é']
# Error 2 (see below)

print f
# Error 1 again
```

Error 1: It tries to decode it as ASCII, for some reason.

```
Traceback (most recent call last):
  File "test2.py", line 13, in <module>
    print f.root._v_children[u'é'.encode('utf-8')]
  File "[...]/tables/misc/proxydict.py", line 40, in __getitem__
    return self._get_value_from_container(self._get_container(), key)
  File "[...]/tables/group.py", line 41, in _get_value_from_container
    return container._f_get_child(key)
  File "[...]/tables/group.py", line 698, in _f_get_child
    self._g_check_has_child(childname)
  File "[...]/tables/group.py", line 391, in _g_check_has_child
    node_type = self._g_get_objinfo(name)
  File "tables/hdf5extension.pyx", line 972, in tables.hdf5extension.Group._g_get_objinfo (tables/hdf5extension.c:11876)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
Closing remaining open files:test.h5...done
```

Error 2: Not surprising, because `keys` returned an encoded version.
```
Traceback (most recent call last):
  File "test2.py", line 11, in <module>
    print f.root._v_children[u'é']
  File "[...]/tables/misc/proxydict.py", line 37, in __getitem__
    raise KeyError(key)
KeyError: u'\xe9'
```
Is there a work-around to this? Can i extract that group without running into these fatal issues? Thanks!

**Comment by FrancescAlted** [comment]
I don't think we have free cycles to spend on improving unicode support on Python 2.7, specially when it is announced that Python 2 will be unmaintained pretty soon.  Closing.
