### ISSUE TITLE
AttributeError: 'IndexArray' object has no attribute 'dirty'

### ISSUE THREAD

**Issue by alobbs** [PyTables/PyTables#656]
I'm seeing the following backtrace using a table with a CSI (using the latest version of the develop branch):

```
Traceback (most recent call last):
  File "/tables/tables/node.py", line 321, in __del__
    self._f_close()
  File "/tables/tables/table.py", line 2957, in _f_close
    self.flush()
  File "/tables/tables/table.py", line 2891, in flush
    self.row._flush_buffered_rows()
  File "tables/tableextension.pyx", line 1334, in tables.tableextension.Row._flush_buffered_rows
  File "/tables/tables/table.py", line 2164, in _save_buffered_rows
    self.flush_rows_to_index(_lastrow=False)
  File "/tables/tables/table.py", line 2517, in flush_rows_to_index
    if nrows > 0 and not col.index.dirty:
AttributeError: 'IndexArray' object has no attribute 'dirty'
```

**Comment by alobbs** [comment]
I'm not sure if a previous `UserWarning: a closed node found in the registry` warning is related.

**Comment by alobbs** [comment]
The 'dirty' workaround (yeah, pun intended) I've temperately added to my tree follows, although it is most certainly not the right fix:

```
diff --git a/tables/table.py b/tables/table.py
index ec140c2..ce6ffde 100644
--- a/tables/table.py
+++ b/tables/table.py
@@ -2523,7 +2523,7 @@ very small/large chunksize, you may want to increase/decrease it."""
             for (colname, colindexed) in six.iteritems(self.colindexed):
                 if colindexed:
                     col = self.cols._g_col(colname)
-                    if nrows > 0 and not col.index.dirty:
+                    if nrows > 0 and (not hasattr(col.index, "dirty") or not col.index.dirty):
                         rowsadded = self._add_rows_to_index(
                             colname, start, nrows, _lastrow, update=True)
             self._unsaved_indexedrows -= rowsadded
```

**Comment by FrancescAlted** [comment]
Is that happening in latest versions of PyTables?  If so, please send a minimal script reproducing this and re-open this ticket.
