### ISSUE TITLE
copy_file problem

### ISSUE THREAD

**Issue by trmrsh** [PyTables/PyTables#691]
tables.File.copy_file does not seem to work, complaining about "no attribute 'iterkeys'" which looks like a python 2-to-3 issue.  I was actually trying to use it to re-write a very large file using L-Z compression, but it fails on just a simple copy operation. Here is some code that does not work:

```python

   # Build a table
   class Data(tables.IsDescription):
       name   = tables.StringCol(32)
       length = tables.Float32Col()
       number = tables.Int32Col()

   h5file = tables.open_file('copy_test.h5', mode='w', title='Copy test')
   table = h5file.create_table(h5file.root, 'ctab', Data)
   row = table.row

   row['name'] = 'First'
   row['length'] = 1.456
   row['number'] = 24
   row.append()

   row['name'] = 'Second'
   row['length'] = 11.8
   row['number'] = 19
   row.append()

   table.flush()
   h5file.close()

   # Now try to copy it
   infile = tables.open_file('copy_test.h5')
   infile.copy_file('copy_test-copy.h5')
```

It comes back with:

    Traceback (most recent call last):
      File "./copy_test.py", line 30, in <module>
        infile.copy_file('copy_test-copy.h5')
      File ".../3.4.6/lib/python3.4/site-packages/tables-3.2.0-py3.4-linux-x86_64.egg/tables/file.py", line 1978, in copy_file
        self.root._f_copy_children(dstfileh.root, recursive=True, **kwargs)
      File ".../3.4.6/lib/python3.4/site-packages/tables-3.2.0-py3.4-linux-x86_64.egg/tables/group.py", line 1079, in _f_copy_children
        for child in self._v_children.values():
      File ".../3.4.6/lib/python3.4/site-packages/tables-3.2.0-py3.4-linux-x86_64.egg/tables/misc/proxydict.py", line 58, in values
        for key in self.iterkeys():
    AttributeError: '_ChildrenDict' object has no attribute 'iterkeys'
    Closing remaining open files:copy_test.h5...done

Apologies if I am doing something stupid.

**Comment by jsancho-gpl** [comment]
Using 3.4.3, it runs properly in my computer. Maybe upgrading will fix your problem.

**Comment by trmrsh** [comment]
Ah thanks. I didn't realise my version was so far behind; I only downloaded it a few days back.
