### ISSUE TITLE
File corruption when "No space left on device" while writing in hdf5 file

### ISSUE THREAD

**Issue by lafrech** [PyTables/PyTables#695]
Hi. Please forgive me if this is a known and obvious issue.

When writing to a hdf5 file, if there is no space left on the device, the write operation fails and the file is corrupted.

I'm using pandas, but from the error messages, it all happens in pytables, so I'm posting here.

To reproduce, let's create a small partition in a virtual filesystem:

```
dd if=/dev/zero of=test.img count=200
mkfs -t ext4 -q test.img
mkdir test
mount test.img test
```

Then run a script that fills the partition:

```python
import pandas as pd
from pandas import HDFStore


df = pd.DataFrame({'data': list(range(1000))}, index=list(range(1000)))

with HDFStore("test/test.h5", 'a', complevel=1, complib='zlib') as store:

    store.append('df0', df)

    while True:
        store.append('df1', df)
```

The write operation fails when writing to `df1`:

```
Traceback (most recent call last):
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/pandas/io/pytables.py", line 4094, in write_data_chunk
    self.table.append(rows)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2236, in append
    self._save_buffered_rows(wbufRA, lenrows)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2173, in _save_buffered_rows
    self.flush_rows_to_index(_lastrow=False)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2528, in flush_rows_to_index
    colname, start, nrows, _lastrow, update=True)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2550, in _add_rows_to_index
    [self._read(startLR, startLR + slicesize, 1, colname)],
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 1858, in _read
    self.row._fill_col(result, start, stop, step, field)
  File "tables/tableextension.pyx", line 1220, in tables.tableextension.Row._fill_col
  File "tables/tableextension.pyx", line 577, in tables.tableextension.Table._read_records
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5Dio.c", line 173, in H5Dread
    can't read data
  File "H5Dio.c", line 554, in H5D__read
    can't read data
  File "H5Dchunk.c", line 1875, in H5D__chunk_read
    unable to read raw data chunk
  File "H5Dchunk.c", line 2993, in H5D__chunk_lock
    unable to preempt chunk(s) from cache
  File "H5Dchunk.c", line 2774, in H5D__chunk_cache_prune
    unable to preempt one or more raw data cache entry
  File "H5Dchunk.c", line 2641, in H5D__chunk_cache_evict
    cannot flush indexed storage buffer
  File "H5Dchunk.c", line 2569, in H5D__chunk_flush_entry
    unable to write raw data to file
  File "H5Fio.c", line 171, in H5F_block_write
    write through metadata accumulator failed
  File "H5Faccum.c", line 825, in H5F__accum_write
    file write failed
  File "H5FDint.c", line 260, in H5FD_write
    driver write request failed
  File "H5FDsec2.c", line 802, in H5FD_sec2_write
    file write failed: time = Thu May 24 15:49:16 2018
, filename = 'test/test.h5', file descriptor = 3, errno = 28, error message = 'No space left on device', buf = 0x55e3ddae6f20, total write size = 974, bytes this sub-write = 974, bytes actually written = 18446744073709551615, offset = 3498589

End of HDF5 error back trace

Problems reading records.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas_hdfstore_disk_full.py", line 17, in <module>
    store.append('df1', df)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/pandas/io/pytables.py", line 987, in append
    **kwargs)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/pandas/io/pytables.py", line 1367, in _write_to_group
    s.write(obj=value, append=append, complib=complib, **kwargs)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/pandas/io/pytables.py", line 3976, in write
    self.write_data(chunksize, dropna=dropna)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/pandas/io/pytables.py", line 4051, in write_data
    values=[v[start_i:end_i] for v in bvalues])
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/pandas/io/pytables.py", line 4097, in write_data_chunk
    raise TypeError("tables cannot write this data -> %s" % detail)
TypeError: tables cannot write this data -> HDF5 error back trace

  File "H5Dio.c", line 173, in H5Dread
    can't read data
  File "H5Dio.c", line 554, in H5D__read
    can't read data
  File "H5Dchunk.c", line 1875, in H5D__chunk_read
    unable to read raw data chunk
  File "H5Dchunk.c", line 2993, in H5D__chunk_lock
    unable to preempt chunk(s) from cache
  File "H5Dchunk.c", line 2774, in H5D__chunk_cache_prune
    unable to preempt one or more raw data cache entry
  File "H5Dchunk.c", line 2641, in H5D__chunk_cache_evict
    cannot flush indexed storage buffer
  File "H5Dchunk.c", line 2569, in H5D__chunk_flush_entry
    unable to write raw data to file
  File "H5Fio.c", line 171, in H5F_block_write
    write through metadata accumulator failed
  File "H5Faccum.c", line 825, in H5F__accum_write
    file write failed
  File "H5FDint.c", line 260, in H5FD_write
    driver write request failed
  File "H5FDsec2.c", line 802, in H5FD_sec2_write
    file write failed: time = Thu May 24 15:49:16 2018
, filename = 'test/test.h5', file descriptor = 3, errno = 28, error message = 'No space left on device', buf = 0x55e3ddae6f20, total write size = 974, bytes this sub-write = 974, bytes actually written = 18446744073709551615, offset = 3498589

End of HDF5 error back trace

Problems reading records.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas_hdfstore_disk_full.py", line 20, in <module>
    print(df)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/pandas/io/pytables.py", line 545, in __exit__
    self.close()
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/pandas/io/pytables.py", line 644, in close
    self._handle.close()
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/file.py", line 2732, in close
    self.root._f_close()
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/group.py", line 937, in _f_close
    self._g_close_descendents()
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/group.py", line 901, in _g_close_descendents
    node_manager.close_subtree(self._v_pathname)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/file.py", line 543, in close_subtree
    self._close_nodes(paths, cache.pop)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/file.py", line 518, in _close_nodes
    node._f_close()
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2966, in _f_close
    self.flush()
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2903, in flush
    rowsadded = self.flush_rows_to_index(_lastrow=True)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2528, in flush_rows_to_index
    colname, start, nrows, _lastrow, update=True)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2550, in _add_rows_to_index
    [self._read(startLR, startLR + slicesize, 1, colname)],
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 1858, in _read
    self.row._fill_col(result, start, stop, step, field)
  File "tables/tableextension.pyx", line 1220, in tables.tableextension.Row._fill_col
  File "tables/tableextension.pyx", line 577, in tables.tableextension.Table._read_records
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5Dio.c", line 173, in H5Dread
    can't read data
  File "H5Dio.c", line 554, in H5D__read
    can't read data
  File "H5Dchunk.c", line 1875, in H5D__chunk_read
    unable to read raw data chunk
  File "H5Dchunk.c", line 2905, in H5D__chunk_lock
    data pipeline read failed
  File "H5Z.c", line 1372, in H5Z_pipeline
    filter returned failure during read
  File "H5Zdeflate.c", line 125, in H5Z_filter_deflate
    inflate() failed

End of HDF5 error back trace

Problems reading records.
Closing remaining open files:test/test.h5...Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/file.py", line 518, in _close_nodes
    node._f_close()
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2966, in _f_close
    self.flush()
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2903, in flush
    rowsadded = self.flush_rows_to_index(_lastrow=True)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2528, in flush_rows_to_index
    colname, start, nrows, _lastrow, update=True)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2550, in _add_rows_to_index
    [self._read(startLR, startLR + slicesize, 1, colname)],
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 1858, in _read
    self.row._fill_col(result, start, stop, step, field)
  File "tables/tableextension.pyx", line 1220, in tables.tableextension.Row._fill_col
  File "tables/tableextension.pyx", line 577, in tables.tableextension.Table._read_records
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5Dio.c", line 173, in H5Dread
    can't read data
  File "H5Dio.c", line 554, in H5D__read
    can't read data
  File "H5Dchunk.c", line 1875, in H5D__chunk_read
    unable to read raw data chunk
  File "H5Dchunk.c", line 2905, in H5D__chunk_lock
    data pipeline read failed
  File "H5Z.c", line 1372, in H5Z_pipeline
    filter returned failure during read
  File "H5Zdeflate.c", line 125, in H5Z_filter_deflate
    inflate() failed

End of HDF5 error back trace
```

Trying to read, I manage to read `df0` but `df1` seems gone for good:

```
Traceback (most recent call last):
  File "pandas_hdfstore_disk_full.py", line 14, in <module>
    df = store.select('df1')
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/pandas/io/pytables.py", line 741, in select
    return it.get_result()
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/pandas/io/pytables.py", line 1483, in get_result
    results = self.func(self.start, self.stop, where)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/pandas/io/pytables.py", line 734, in func
    columns=columns)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/pandas/io/pytables.py", line 4180, in read
    if not self.read_axes(where=where, **kwargs):
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/pandas/io/pytables.py", line 3377, in read_axes
    values = self.selection.select()
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/pandas/io/pytables.py", line 4779, in select
    return self.table.table.read(start=self.start, stop=self.stop)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 1935, in read
    arr = self._read(start, stop, step, field, out)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 1849, in _read
    self._read_records(start, stop - start, result)
  File "tables/tableextension.pyx", line 577, in tables.tableextension.Table._read_records
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5Dio.c", line 173, in H5Dread
    can't read data
  File "H5Dio.c", line 554, in H5D__read
    can't read data
  File "H5Dchunk.c", line 1875, in H5D__chunk_read
    unable to read raw data chunk
  File "H5Dchunk.c", line 2905, in H5D__chunk_lock
    data pipeline read failed
  File "H5Z.c", line 1372, in H5Z_pipeline
    filter returned failure during read
  File "H5Zdeflate.c", line 125, in H5Z_filter_deflate
    inflate() failed

End of HDF5 error back trace

Problems reading records.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas_hdfstore_disk_full.py", line 15, in <module>
    print(df)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/pandas/io/pytables.py", line 545, in __exit__
    self.close()
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/pandas/io/pytables.py", line 644, in close
    self._handle.close()
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/file.py", line 2732, in close
    self.root._f_close()
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/group.py", line 937, in _f_close
    self._g_close_descendents()
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/group.py", line 901, in _g_close_descendents
    node_manager.close_subtree(self._v_pathname)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/file.py", line 543, in close_subtree
    self._close_nodes(paths, cache.pop)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/file.py", line 518, in _close_nodes
    node._f_close()
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2966, in _f_close
    self.flush()
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2903, in flush
    rowsadded = self.flush_rows_to_index(_lastrow=True)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2528, in flush_rows_to_index
    colname, start, nrows, _lastrow, update=True)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2550, in _add_rows_to_index
    [self._read(startLR, startLR + slicesize, 1, colname)],
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 1858, in _read
    self.row._fill_col(result, start, stop, step, field)
  File "tables/tableextension.pyx", line 1220, in tables.tableextension.Row._fill_col
  File "tables/tableextension.pyx", line 577, in tables.tableextension.Table._read_records
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5Dio.c", line 173, in H5Dread
    can't read data
  File "H5Dio.c", line 554, in H5D__read
    can't read data
  File "H5Dchunk.c", line 1875, in H5D__chunk_read
    unable to read raw data chunk
  File "H5Dchunk.c", line 2905, in H5D__chunk_lock
    data pipeline read failed
  File "H5Z.c", line 1372, in H5Z_pipeline
    filter returned failure during read
  File "H5Zdeflate.c", line 125, in H5Z_filter_deflate
    inflate() failed

End of HDF5 error back trace

Problems reading records.
Closing remaining open files:test/test.h5...Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/file.py", line 518, in _close_nodes
    node._f_close()
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2966, in _f_close
    self.flush()
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2903, in flush
    rowsadded = self.flush_rows_to_index(_lastrow=True)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2528, in flush_rows_to_index
    colname, start, nrows, _lastrow, update=True)
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 2550, in _add_rows_to_index
    [self._read(startLR, startLR + slicesize, 1, colname)],
  File "/home/jerome/.virtualenvs/pytables/lib/python3.5/site-packages/tables/table.py", line 1858, in _read
    self.row._fill_col(result, start, stop, step, field)
  File "tables/tableextension.pyx", line 1220, in tables.tableextension.Row._fill_col
  File "tables/tableextension.pyx", line 577, in tables.tableextension.Table._read_records
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5Dio.c", line 173, in H5Dread
    can't read data
  File "H5Dio.c", line 554, in H5D__read
    can't read data
  File "H5Dchunk.c", line 1875, in H5D__chunk_read
    unable to read raw data chunk
  File "H5Dchunk.c", line 2905, in H5D__chunk_lock
    data pipeline read failed
  File "H5Z.c", line 1372, in H5Z_pipeline
    filter returned failure during read
  File "H5Zdeflate.c", line 125, in H5Z_filter_deflate
    inflate() failed

End of HDF5 error back trace

Problems reading records.
```

I did a quick search to see if other people already faced the same issue.

Any advice how to handle this gracefully?

[Related post in hdfgroup forums](https://forum.hdfgroup.org/t/avoid-file-corruption-due-to-disk-space-shortage/2494/1)

**Comment by FrancescAlted** [comment]
Yeah, HDF5 is not really meant to protect the file when there is no space left on the disk.  A possible workaround would be to check for free space in filesystem before doing the append.  This can be done inside PyTables, but I think the best place would be the user code, otherwise the checks for free space on the disk would unnecessarily slow down the appends for the general case.
