### ISSUE TITLE
Exception on updating index after setting complex field 

### ISSUE THREAD

**Issue by ihormelnyk** [PyTables/PyTables#699]
```
import tables as tb
import numpy as np

date_t = np.dtype([('year', np.int32), ('month', np.int32), ('day', np.int32)])
record_t = np.dtype([('id', np.int32), ('date', date_t)])
data = np.zeros(5, record_t)

filename = "test.h5"
with tb.open_file(filename, "w") as f:
    table = f.create_table("/", "test_table", data)
    f.root.test_table.cols.id.create_csindex()
    for row in f.root.test_table.iterrows():
        row['date'] = (2018, 6, 22)
        row.update()
```
Stack trace:
```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    for row in f.root.test_table.iterrows():
  File "tables\tableextension.pyx", line 905, in tables.tableextension.Row.__next__
  File "tables\tableextension.pyx", line 1151, in tables.tableextension.Row.__next__general
  File "tables\tableextension.pyx", line 1189, in tables.tableextension.Row._finish_riterator
  File "tables\tableextension.pyx", line 1429, in tables.tableextension.Row._flush_mod_rows
  File "c:\Python27Pt\lib\site-packages\tables\table.py", line 2715, in _mark_columns_as_dirty
    if colindexed[colname]:
KeyError: 'date'
```

**Comment by FrancescAlted** [comment]
Yeah, that should be some hipcup with the index creation.  A quick workaround would be to create the index *after* populating the table (this is more efficient too).

**Comment by ihormelnyk** [comment]
Its just sample to show all conditions. Real scenario much more complex. Issue appears after modification existing file with index
