### ISSUE TITLE
Snappy dependency for conda package manager

### ISSUE THREAD

**Issue by baspet010** [PyTables/PyTables#705]
Hi can you add snappy to the dependencies for anaconda package manager?

I get the following error when importing tables after installation of pytables with `conda install pytables`:

```
Microsoft Windows [Version 10.0.17134.165]
(c) 2018 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\peterek>conda create -n pytables_test_env
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Miniconda3\envs\pytables_test_env


Proceed ([y]/n)?

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use:
# > activate pytables_test_env
#
# To deactivate an active environment, use:
# > deactivate
#
# * for power-users using bash, you must source
#


C:\Users\peterek>activate pytables_test_env

(pytables_test_env) C:\Users\peterek>
(pytables_test_env) C:\Users\peterek>conda install pytables
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Miniconda3\envs\pytables_test_env

  added / updated specs:
    - pytables


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2018.4.16          |           py36_0         143 KB  conda-forge

The following NEW packages will be INSTALLED:

    blosc:          1.14.0-h6538335_1     conda-forge
    bzip2:          1.0.6-hfa6e2cd_2      conda-forge
    certifi:        2018.4.16-py36_0      conda-forge
    hdf5:           1.10.1-h98b8871_1
    icc_rt:         2017.0.4-h97af966_0
    intel-openmp:   2018.0.3-0
    mkl:            2018.0.3-1
    mkl_fft:        1.0.3-py36_0          conda-forge
    mkl_random:     1.0.1-py36_0          conda-forge
    numexpr:        2.6.5-py36_0          conda-forge
    numpy:          1.14.3-py36h9fa60d3_2
    numpy-base:     1.14.3-py36h5c71026_0
    pip:            9.0.3-py36_0          conda-forge
    pytables:       3.4.4-py36_8          conda-forge
    python:         3.6.6-hea74fb7_0
    setuptools:     40.0.0-py36_0         conda-forge
    six:            1.11.0-py36_1         conda-forge
    vc:             14.1-h0510ff6_3
    vs2015_runtime: 15.5.2-3
    wheel:          0.31.1-py36_0         conda-forge
    wincertstore:   0.2-py36_1            conda-forge
    zlib:           1.2.11-h2fa13f4_3     conda-forge

Proceed ([y]/n)?


Downloading and Extracting Packages
certifi-2018.4.16    |  143 KB | ################################################################################################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(pytables_test_env) C:\Users\peterek>conda list
# packages in environment at C:\ProgramData\Miniconda3\envs\pytables_test_env:
#
# Name                    Version                   Build  Channel
blosc                     1.14.0               h6538335_1    conda-forge
bzip2                     1.0.6                hfa6e2cd_2    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
hdf5                      1.10.1               h98b8871_1
icc_rt                    2017.0.4             h97af966_0
intel-openmp              2018.0.3                      0
mkl                       2018.0.3                      1
mkl_fft                   1.0.3                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
numexpr                   2.6.5                    py36_0    conda-forge
numpy                     1.14.3           py36h9fa60d3_2
numpy-base                1.14.3           py36h5c71026_0
pip                       9.0.3                    py36_0    conda-forge
pytables                  3.4.4                    py36_8    conda-forge
python                    3.6.6                hea74fb7_0
setuptools                40.0.0                   py36_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
vc                        14.1                 h0510ff6_3
vs2015_runtime            15.5.2                        3
wheel                     0.31.1                   py36_0    conda-forge
wincertstore              0.2                      py36_1    conda-forge
zlib                      1.2.11               h2fa13f4_3    conda-forge

(pytables_test_env) C:\Users\peterek>
(pytables_test_env) C:\Users\peterek>python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tables
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\envs\pytables_test_env\lib\site-packages\tables\__init__.py", line 93, in <module>
    from .utilsextension import (
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
>>> 
```

After installing snappy with `conda install snappy` I don't get that error anymore, see:

```
(pytables_test_env) C:\Users\peterek>conda install snappy
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Miniconda3\envs\pytables_test_env

  added / updated specs:
    - snappy


The following NEW packages will be INSTALLED:

    snappy: 1.1.7-h6538335_2 conda-forge

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(pytables_test_env) C:\Users\peterek>conda list
# packages in environment at C:\ProgramData\Miniconda3\envs\pytables_test_env:
#
# Name                    Version                   Build  Channel
blosc                     1.14.0               h6538335_1    conda-forge
bzip2                     1.0.6                hfa6e2cd_2    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
hdf5                      1.10.1               h98b8871_1
icc_rt                    2017.0.4             h97af966_0
intel-openmp              2018.0.3                      0
mkl                       2018.0.3                      1
mkl_fft                   1.0.3                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
numexpr                   2.6.5                    py36_0    conda-forge
numpy                     1.14.3           py36h9fa60d3_2
numpy-base                1.14.3           py36h5c71026_0
pip                       9.0.3                    py36_0    conda-forge
pytables                  3.4.4                    py36_8    conda-forge
python                    3.6.6                hea74fb7_0
setuptools                40.0.0                   py36_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
snappy                    1.1.7                h6538335_2    conda-forge
vc                        14.1                 h0510ff6_3
vs2015_runtime            15.5.2                        3
wheel                     0.31.1                   py36_0    conda-forge
wincertstore              0.2                      py36_1    conda-forge
zlib                      1.2.11               h2fa13f4_3    conda-forge

(pytables_test_env) C:\Users\peterek>
(pytables_test_env) C:\Users\peterek>python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tables
>>>
```

So can you please add snappy to the dependencies for pytables.
Thanks.

**Comment by tomkooij** [comment]
This is related to: https://github.com/conda-forge/pytables-feedstock/issues/31

**Comment by FrancescAlted** [comment]
Looks like this is out of scope here.  Closing.
