### ISSUE TITLE
Python 3.8.0a4 RuntimeError: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by cgohlke** [PyTables/PyTables#733]
I get 11 test errors on Python 3.8.0a4 due to https://github.com/python/cpython/pull/12596

```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.5.1
HDF5 version:        1.10.5
NumPy version:       1.15.4
Numexpr version:     2.6.9 (using VML/MKL 2019.0.4)
Zlib version:        1.2.11 (in Python interpreter)
BZIP2 version:       1.0.6 (6-Sept-2010)
Blosc version:       1.16.3 (2019-03-08)
Blosc compressors:   blosclz (1.1.0), lz4 (1.9.0), lz4hc (1.9.0), snappy (unknown), zlib (1.2.11), zstd (1.4.0)
Blosc filters:       shuffle, bitshuffle
Cython version:      3.0a0
Python version:      3.8.0a4 (v3.8.0a4:c1004b8546, May  7 2019, 13:53:12) [MSC v.1916 64 bit (AMD64)]
Platform:            Windows-10-10.0.17763-SP0
Byte-ordering:       little
Detected cores:      12
Default encoding:    utf-8
Default FS encoding: utf-8
Default locale:      (en_US, cp1252)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Performing only a light (yet comprehensive) subset of the test suite.
If you want a more complete test, try passing the --heavy flag to this script
(or set the 'heavy' parameter in case you are using tables.test() call).
The whole suite will take more than 4 hours to complete on a relatively
modern CPU and around 512 MB of main memory.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
X:\Python38\lib\site-packages\tables\filters.py:329: FiltersWarning: compression library ``lzo`` is not available; using ``zlib`` instead
  warnings.warn("compression library ``%s`` is not available; "

<snip>

X:\Python38\lib\site-packages\tables\nodes\filenode.py:170: UserWarning: host PyTables file is already closed!
  warnings.warn("host PyTables file is already closed!")
......
======================================================================
ERROR: None (tables.tests.test_basics.NoNodeCacheOpenFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python38\lib\site-packages\tables\tests\test_basics.py", line 565, in test09e_renameGroup
    self.h5file.rename_node('/', name='agroup', newname='agroup_')
  File "X:\Python38\lib\site-packages\tables\file.py", line 1701, in rename_node
    obj._f_rename(newname, overwrite)
  File "X:\Python38\lib\site-packages\tables\node.py", line 605, in _f_rename
    self._f_move(newname=newname, overwrite=overwrite)
  File "X:\Python38\lib\site-packages\tables\node.py", line 689, in _f_move
    self._g_move(newparent, newname)
  File "X:\Python38\lib\site-packages\tables\group.py", line 602, in _g_move
    self._v_file._update_node_locations(oldpath, newpath)
  File "X:\Python38\lib\site-packages\tables\file.py", line 2852, in _update_node_locations
    for nodepath in cache:
  File "X:\Python38\lib\weakref.py", line 223, in keys
    for k, wr in self.data.items():
RuntimeError: dictionary keys changed during iteration

======================================================================
ERROR: None (tables.tests.test_indexes.BasicReadTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python38\lib\site-packages\tables\tests\test_indexes.py", line 566, in test10d_moveIndex
    table.move(agroup, "table2")
  File "X:\Python38\lib\site-packages\tables\leaf.py", line 625, in move
    self._f_move(newparent, newname, overwrite, createparents)
  File "X:\Python38\lib\site-packages\tables\node.py", line 689, in _f_move
    self._g_move(newparent, newname)
  File "X:\Python38\lib\site-packages\tables\table.py", line 2679, in _g_move
    itgroup._g_move(newigroup, newiname)
  File "X:\Python38\lib\site-packages\tables\group.py", line 602, in _g_move
    self._v_file._update_node_locations(oldpath, newpath)
  File "X:\Python38\lib\site-packages\tables\file.py", line 2852, in _update_node_locations
    for nodepath in cache:
  File "X:\Python38\lib\weakref.py", line 223, in keys
    for k, wr in self.data.items():
RuntimeError: dictionary keys changed during iteration

======================================================================
ERROR: None (tables.tests.test_indexes.ZlibReadTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python38\lib\site-packages\tables\tests\test_indexes.py", line 566, in test10d_moveIndex
    table.move(agroup, "table2")
  File "X:\Python38\lib\site-packages\tables\leaf.py", line 625, in move
    self._f_move(newparent, newname, overwrite, createparents)
  File "X:\Python38\lib\site-packages\tables\node.py", line 689, in _f_move
    self._g_move(newparent, newname)
  File "X:\Python38\lib\site-packages\tables\table.py", line 2679, in _g_move
    itgroup._g_move(newigroup, newiname)
  File "X:\Python38\lib\site-packages\tables\group.py", line 602, in _g_move
    self._v_file._update_node_locations(oldpath, newpath)
  File "X:\Python38\lib\site-packages\tables\file.py", line 2852, in _update_node_locations
    for nodepath in cache:
  File "X:\Python38\lib\weakref.py", line 223, in keys
    for k, wr in self.data.items():
RuntimeError: dictionary keys changed during iteration

======================================================================
ERROR: None (tables.tests.test_indexes.BloscReadTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python38\lib\site-packages\tables\tests\test_indexes.py", line 566, in test10d_moveIndex
    table.move(agroup, "table2")
  File "X:\Python38\lib\site-packages\tables\leaf.py", line 625, in move
    self._f_move(newparent, newname, overwrite, createparents)
  File "X:\Python38\lib\site-packages\tables\node.py", line 689, in _f_move
    self._g_move(newparent, newname)
  File "X:\Python38\lib\site-packages\tables\table.py", line 2679, in _g_move
    itgroup._g_move(newigroup, newiname)
  File "X:\Python38\lib\site-packages\tables\group.py", line 602, in _g_move
    self._v_file._update_node_locations(oldpath, newpath)
  File "X:\Python38\lib\site-packages\tables\file.py", line 2852, in _update_node_locations
    for nodepath in cache:
  File "X:\Python38\lib\weakref.py", line 223, in keys
    for k, wr in self.data.items():
RuntimeError: dictionary keys changed during iteration

======================================================================
ERROR: None (tables.tests.test_indexes.Bzip2ReadTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python38\lib\site-packages\tables\tests\test_indexes.py", line 566, in test10d_moveIndex
    table.move(agroup, "table2")
  File "X:\Python38\lib\site-packages\tables\leaf.py", line 625, in move
    self._f_move(newparent, newname, overwrite, createparents)
  File "X:\Python38\lib\site-packages\tables\node.py", line 689, in _f_move
    self._g_move(newparent, newname)
  File "X:\Python38\lib\site-packages\tables\table.py", line 2679, in _g_move
    itgroup._g_move(newigroup, newiname)
  File "X:\Python38\lib\site-packages\tables\group.py", line 602, in _g_move
    self._v_file._update_node_locations(oldpath, newpath)
  File "X:\Python38\lib\site-packages\tables\file.py", line 2852, in _update_node_locations
    for nodepath in cache:
  File "X:\Python38\lib\weakref.py", line 223, in keys
    for k, wr in self.data.items():
RuntimeError: dictionary keys changed during iteration

======================================================================
ERROR: None (tables.tests.test_indexes.ShuffleReadTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python38\lib\site-packages\tables\tests\test_indexes.py", line 566, in test10d_moveIndex
    table.move(agroup, "table2")
  File "X:\Python38\lib\site-packages\tables\leaf.py", line 625, in move
    self._f_move(newparent, newname, overwrite, createparents)
  File "X:\Python38\lib\site-packages\tables\node.py", line 689, in _f_move
    self._g_move(newparent, newname)
  File "X:\Python38\lib\site-packages\tables\table.py", line 2679, in _g_move
    itgroup._g_move(newigroup, newiname)
  File "X:\Python38\lib\site-packages\tables\group.py", line 602, in _g_move
    self._v_file._update_node_locations(oldpath, newpath)
  File "X:\Python38\lib\site-packages\tables\file.py", line 2852, in _update_node_locations
    for nodepath in cache:
  File "X:\Python38\lib\weakref.py", line 223, in keys
    for k, wr in self.data.items():
RuntimeError: dictionary keys changed during iteration

======================================================================
ERROR: None (tables.tests.test_indexes.Fletcher32ReadTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python38\lib\site-packages\tables\tests\test_indexes.py", line 566, in test10d_moveIndex
    table.move(agroup, "table2")
  File "X:\Python38\lib\site-packages\tables\leaf.py", line 625, in move
    self._f_move(newparent, newname, overwrite, createparents)
  File "X:\Python38\lib\site-packages\tables\node.py", line 689, in _f_move
    self._g_move(newparent, newname)
  File "X:\Python38\lib\site-packages\tables\table.py", line 2679, in _g_move
    itgroup._g_move(newigroup, newiname)
  File "X:\Python38\lib\site-packages\tables\group.py", line 602, in _g_move
    self._v_file._update_node_locations(oldpath, newpath)
  File "X:\Python38\lib\site-packages\tables\file.py", line 2852, in _update_node_locations
    for nodepath in cache:
  File "X:\Python38\lib\weakref.py", line 223, in keys
    for k, wr in self.data.items():
RuntimeError: dictionary keys changed during iteration

======================================================================
ERROR: None (tables.tests.test_indexes.ShuffleFletcher32ReadTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python38\lib\site-packages\tables\tests\test_indexes.py", line 566, in test10d_moveIndex
    table.move(agroup, "table2")
  File "X:\Python38\lib\site-packages\tables\leaf.py", line 625, in move
    self._f_move(newparent, newname, overwrite, createparents)
  File "X:\Python38\lib\site-packages\tables\node.py", line 689, in _f_move
    self._g_move(newparent, newname)
  File "X:\Python38\lib\site-packages\tables\table.py", line 2679, in _g_move
    itgroup._g_move(newigroup, newiname)
  File "X:\Python38\lib\site-packages\tables\group.py", line 602, in _g_move
    self._v_file._update_node_locations(oldpath, newpath)
  File "X:\Python38\lib\site-packages\tables\file.py", line 2852, in _update_node_locations
    for nodepath in cache:
  File "X:\Python38\lib\weakref.py", line 223, in keys
    for k, wr in self.data.items():
RuntimeError: dictionary keys changed during iteration

======================================================================
ERROR: None (tables.tests.test_indexes.OneHalfTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python38\lib\site-packages\tables\tests\test_indexes.py", line 566, in test10d_moveIndex
    table.move(agroup, "table2")
  File "X:\Python38\lib\site-packages\tables\leaf.py", line 625, in move
    self._f_move(newparent, newname, overwrite, createparents)
  File "X:\Python38\lib\site-packages\tables\node.py", line 689, in _f_move
    self._g_move(newparent, newname)
  File "X:\Python38\lib\site-packages\tables\table.py", line 2679, in _g_move
    itgroup._g_move(newigroup, newiname)
  File "X:\Python38\lib\site-packages\tables\group.py", line 602, in _g_move
    self._v_file._update_node_locations(oldpath, newpath)
  File "X:\Python38\lib\site-packages\tables\file.py", line 2852, in _update_node_locations
    for nodepath in cache:
  File "X:\Python38\lib\weakref.py", line 223, in keys
    for k, wr in self.data.items():
RuntimeError: dictionary keys changed during iteration

======================================================================
ERROR: None (tables.tests.test_indexes.UpperBoundTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python38\lib\site-packages\tables\tests\test_indexes.py", line 566, in test10d_moveIndex
    table.move(agroup, "table2")
  File "X:\Python38\lib\site-packages\tables\leaf.py", line 625, in move
    self._f_move(newparent, newname, overwrite, createparents)
  File "X:\Python38\lib\site-packages\tables\node.py", line 689, in _f_move
    self._g_move(newparent, newname)
  File "X:\Python38\lib\site-packages\tables\table.py", line 2679, in _g_move
    itgroup._g_move(newigroup, newiname)
  File "X:\Python38\lib\site-packages\tables\group.py", line 602, in _g_move
    self._v_file._update_node_locations(oldpath, newpath)
  File "X:\Python38\lib\site-packages\tables\file.py", line 2852, in _update_node_locations
    for nodepath in cache:
  File "X:\Python38\lib\weakref.py", line 223, in keys
    for k, wr in self.data.items():
RuntimeError: dictionary keys changed during iteration

======================================================================
ERROR: None (tables.tests.test_indexes.LowerBoundTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python38\lib\site-packages\tables\tests\test_indexes.py", line 566, in test10d_moveIndex
    table.move(agroup, "table2")
  File "X:\Python38\lib\site-packages\tables\leaf.py", line 625, in move
    self._f_move(newparent, newname, overwrite, createparents)
  File "X:\Python38\lib\site-packages\tables\node.py", line 689, in _f_move
    self._g_move(newparent, newname)
  File "X:\Python38\lib\site-packages\tables\table.py", line 2679, in _g_move
    itgroup._g_move(newigroup, newiname)
  File "X:\Python38\lib\site-packages\tables\group.py", line 602, in _g_move
    self._v_file._update_node_locations(oldpath, newpath)
  File "X:\Python38\lib\site-packages\tables\file.py", line 2852, in _update_node_locations
    for nodepath in cache:
  File "X:\Python38\lib\weakref.py", line 223, in keys
    for k, wr in self.data.items():
RuntimeError: dictionary keys changed during iteration

----------------------------------------------------------------------
Ran 6388 tests in 172.980s

FAILED (errors=11, skipped=193)
```

**Comment by tomkooij** [comment]
I'm trying to build pytables against `python 3.8.0a4` but I'm stuck a numpy which will not build because of a Cython incompatibility against 3.8: https://github.com/cython/cython/issues/2938

When I have a working build, I'll try to sort this one out...

**Comment by hroncok** [comment]
We have the same problem in Fedora. How can I help you set up your environment? Would a Dockerfile work for you?

**Comment by hroncok** [comment]
Here's how to run the testusite:

```
$ git clone https://github.com/cython/cython
$ git clone https://github.com/numpy/numpy
$ git clone https://github.com/PyTables/PyTables

$ python3.8 -m venv __venv__
$ . __venv__/bin/activate
$ (__venv__) $ python --version
Python 3.8.0a4

(__venv__) $ cd cython/
(__venv__) [cython (master)]$ git checkout 0.29.x
(__venv__) [cython (0.29.x)]$ git pull origin refs/pull/2954/head
(__venv__) [cython (0.29.x)]$ python -m pip install . --install-option="--no-cython-compile"

(__venv__) [cython (0.29.x)]$ cd ../numpy/
(__venv__) [numpy (master)]$ git checkout v1.16.3
(__venv__) [numpy ((v1.16.3))]$ pip install .

(__venv__) [numpy ((v1.16.3))]$ cd ../PyTables/
(__venv__) [PyTables (master)]$ python -m pip install .
(__venv__) [PyTables (master)]$ cd ..

(__venv__) $ python -m tables.tests.test_all
/usr/lib64/python3.8/runpy.py:125: RuntimeWarning: 'tables.tests.test_all' found in sys.modules after import of package 'tables.tests', but prior to execution of 'tables.tests.test_all'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.5.2.dev0
HDF5 version:        1.8.20
NumPy version:       1.16.3
Numexpr version:     2.6.9 (not using Intel's VML/MKL)
Zlib version:        1.2.11 (in Python interpreter)
LZO version:         2.08 (Jun 29 2014)
BZIP2 version:       1.0.6 (6-Sept-2010)
Blosc version:       1.14.4 (2018-07-30)
Blosc compressors:   blosclz (1.1.0), lz4 (1.8.3), lz4hc (1.8.3), snappy (unknown), zlib (1.2.11), zstd (1.3.8)
Blosc filters:       shuffle, bitshuffle
Cython version:      0.29.7
Python version:      3.8.0a4 (default, May 17 2019, 21:21:00) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
Platform:            Linux-5.0.16-300.fc30.x86_64-x86_64-with-glibc2.2.5
Byte-ordering:       little
Detected cores:      8
Default encoding:    utf-8
Default FS encoding: utf-8
Default locale:      (en_US, UTF-8)
```

**Comment by tomkooij** [comment]
@hroncok : Thanks, I'm going to try and replicate your workflow (and hopefully fix my cython problems).

**Comment by hroncok** [comment]
based on Cython issues progress, I've edited the procedure to use https://github.com/cython/cython/pull/2971 instead of https://github.com/cython/cython/pull/2954

**Comment by cgohlke** [comment]
Thank you. All tests pass now with Python 3.8.0a4 on Windows.
