### ISSUE TITLE
tests fail on s390x with AttributeError: 'UnImplemented' object has no attribute 'cols'

### ISSUE THREAD

**Issue by keszybz** [PyTables/PyTables#735]
I'm trying to build pytables 3.5.1 on s390x (in Fedora). The tests fail on one architecture:
```
+ /usr/bin/python2 bench/check_all.py
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.5.1
HDF5 version:        1.10.5
NumPy version:       1.16.3
Numexpr version:     2.6.6 (not using Intel's VML/MKL)
Zlib version:        1.2.11 (in Python interpreter)
LZO version:         2.08 (Jun 29 2014)
BZIP2 version:       1.0.6 (6-Sept-2010)
Blosc version:       1.16.3 (2019-03-08)
Blosc compressors:   blosclz (1.1.0), lz4 (1.8.3), lz4hc (1.8.3), snappy (unknown), zlib (1.2.11), zstd (1.4.0)
Blosc filters:       shuffle, bitshuffle
Python version:      2.7.16 (default, Apr 30 2019, 15:17:54) 
[GCC 9.0.1 20190426 (Red Hat 9.0.1-0.15)]
Platform:            Linux-5.0.13-200.fc29.s390x-s390x-with-fedora-31-Rawhide
Byte-ordering:       big
Detected cores:      2
Default encoding:    ascii
Default FS encoding: ANSI_X3.4-1968
Default locale:      (None, None)
...
BUILDSTDERR: Checking for uncollectable garbage. ... ok
BUILDSTDERR: ======================================================================
BUILDSTDERR: ERROR: test00_version (tables.tests.test_index_backcompat.Indexes2_0TestCase)
BUILDSTDERR: Checking index version.
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/builddir/build/BUILDROOT/python-tables-3.5.1-1.fc31.s390x/usr/lib64/python2.7/site-packages/tables/tests/test_index_backcompat.py", line 21, in setUp
BUILDSTDERR:     self.sl = self.table1.cols.var1.index.slicesize
BUILDSTDERR: AttributeError: 'UnImplemented' object has no attribute 'cols'
BUILDSTDERR: ======================================================================
BUILDSTDERR: ERROR: test01_string (tables.tests.test_index_backcompat.Indexes2_0TestCase)
BUILDSTDERR: Checking string indexes.
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/builddir/build/BUILDROOT/python-tables-3.5.1-1.fc31.s390x/usr/lib64/python2.7/site-packages/tables/tests/test_index_backcompat.py", line 21, in setUp
BUILDSTDERR:     self.sl = self.table1.cols.var1.index.slicesize
BUILDSTDERR: AttributeError: 'UnImplemented' object has no attribute 'cols'
BUILDSTDERR: ======================================================================
BUILDSTDERR: ERROR: test02_bool (tables.tests.test_index_backcompat.Indexes2_0TestCase)
BUILDSTDERR: Checking bool indexes.
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/builddir/build/BUILDROOT/python-tables-3.5.1-1.fc31.s390x/usr/lib64/python2.7/site-packages/tables/tests/test_index_backcompat.py", line 21, in setUp
BUILDSTDERR:     self.sl = self.table1.cols.var1.index.slicesize
BUILDSTDERR: AttributeError: 'UnImplemented' object has no attribute 'cols'
BUILDSTDERR: ======================================================================
BUILDSTDERR: ERROR: test03_int (tables.tests.test_index_backcompat.Indexes2_0TestCase)
BUILDSTDERR: Checking int indexes.
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/builddir/build/BUILDROOT/python-tables-3.5.1-1.fc31.s390x/usr/lib64/python2.7/site-packages/tables/tests/test_index_backcompat.py", line 21, in setUp
BUILDSTDERR:     self.sl = self.table1.cols.var1.index.slicesize
BUILDSTDERR: AttributeError: 'UnImplemented' object has no attribute 'cols'
BUILDSTDERR: ======================================================================
BUILDSTDERR: ERROR: test04_float (tables.tests.test_index_backcompat.Indexes2_0TestCase)
BUILDSTDERR: Checking float indexes.
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/builddir/build/BUILDROOT/python-tables-3.5.1-1.fc31.s390x/usr/lib64/python2.7/site-packages/tables/tests/test_index_backcompat.py", line 21, in setUp
BUILDSTDERR:     self.sl = self.table1.cols.var1.index.slicesize
BUILDSTDERR: AttributeError: 'UnImplemented' object has no attribute 'cols'
BUILDSTDERR: ======================================================================
BUILDSTDERR: ERROR: test00_version (tables.tests.test_index_backcompat.Indexes2_1TestCase)
BUILDSTDERR: Checking index version.
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/builddir/build/BUILDROOT/python-tables-3.5.1-1.fc31.s390x/usr/lib64/python2.7/site-packages/tables/tests/test_index_backcompat.py", line 21, in setUp
BUILDSTDERR:     self.sl = self.table1.cols.var1.index.slicesize
BUILDSTDERR: AttributeError: 'UnImplemented' object has no attribute 'cols'
BUILDSTDERR: ======================================================================
BUILDSTDERR: ERROR: test01_string (tables.tests.test_index_backcompat.Indexes2_1TestCase)
BUILDSTDERR: Checking string indexes.
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/builddir/build/BUILDROOT/python-tables-3.5.1-1.fc31.s390x/usr/lib64/python2.7/site-packages/tables/tests/test_index_backcompat.py", line 21, in setUp
BUILDSTDERR:     self.sl = self.table1.cols.var1.index.slicesize
BUILDSTDERR: AttributeError: 'UnImplemented' object has no attribute 'cols'
BUILDSTDERR: ======================================================================
BUILDSTDERR: ERROR: test02_bool (tables.tests.test_index_backcompat.Indexes2_1TestCase)
BUILDSTDERR: Checking bool indexes.
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/builddir/build/BUILDROOT/python-tables-3.5.1-1.fc31.s390x/usr/lib64/python2.7/site-packages/tables/tests/test_index_backcompat.py", line 21, in setUp
BUILDSTDERR:     self.sl = self.table1.cols.var1.index.slicesize
BUILDSTDERR: AttributeError: 'UnImplemented' object has no attribute 'cols'
BUILDSTDERR: ======================================================================
BUILDSTDERR: ERROR: test03_int (tables.tests.test_index_backcompat.Indexes2_1TestCase)
BUILDSTDERR: Checking int indexes.
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/builddir/build/BUILDROOT/python-tables-3.5.1-1.fc31.s390x/usr/lib64/python2.7/site-packages/tables/tests/test_index_backcompat.py", line 21, in setUp
BUILDSTDERR:     self.sl = self.table1.cols.var1.index.slicesize
BUILDSTDERR: AttributeError: 'UnImplemented' object has no attribute 'cols'
BUILDSTDERR: ======================================================================
BUILDSTDERR: ERROR: test04_float (tables.tests.test_index_backcompat.Indexes2_1TestCase)
BUILDSTDERR: Checking float indexes.
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Traceback (most recent call last):
BUILDSTDERR:   File "/builddir/build/BUILDROOT/python-tables-3.5.1-1.fc31.s390x/usr/lib64/python2.7/site-packages/tables/tests/test_index_backcompat.py", line 21, in setUp
BUILDSTDERR:     self.sl = self.table1.cols.var1.index.slicesize
BUILDSTDERR: AttributeError: 'UnImplemented' object has no attribute 'cols'
BUILDSTDERR: ----------------------------------------------------------------------
BUILDSTDERR: Ran 6385 tests in 122.441s
BUILDSTDERR: FAILED (errors=10, skipped=27)
```

Full log: https://kojipkgs.fedoraproject.org//work/tasks/3058/34993058/build.log
Build: https://koji.fedoraproject.org/koji/taskinfo?taskID=34993036

**Comment by keszybz** [comment]
Oh, I didn't see this before:
```
BUILDSTDERR: Checking index version. ... /builddir/build/BUILDROOT/python-tables-3.5.1-1.fc31.s390x/usr/lib64/python2.7/site-packages/tables/group.py:1208: UserWarning: problems loading leaf ``/table1``::
BUILDSTDERR:   Wrong slicesize
BUILDSTDERR: The leaf will become an ``UnImplemented`` node.
BUILDSTDERR:   % (self._g_join(childname), exc))
BUILDSTDERR: ERROR
```
So that explains where UnImplemented came from.

**Comment by FrancescAlted** [comment]
Ok.  That makes sense.  Big endian architectures have not been too much tested, and this error is probably a sign that indexes in PyTables files are not portable between little and big endian machines.  But apparently there are no more errors, so hopefully this is the only issue in big endian platforms.

**Comment by avalentino** [comment]
The origin seems to be an assertion failure in index.py: Indec._g_post_init_hook:

```
assert self.slicesize == indices.shape[1], "Wrong slicesize"
```

I don't think that relevant code for indexing has been changed recently and I suppose that previous builds on s390x worked fine.
It would be interesting to know which is the change that triggered the issue: gcc version , hdf5 version, build flags?

@keszybz do you have he possibility to investigate the problem on the s390x platform?

It is very hard to track down the issue without having access to the target machine and having the possibility to reproduce.

@FrancescAlted the issue seems to affect only compatibilty code for indexing, do you think it is something that can be dropped? It should not result in a data loss in any case if my understanding is correct.

**Comment by FrancescAlted** [comment]
Ok, I was not really conscious that tests were passing in s390x architectures before, so probably worth to spend some time looking at what caused this (hdf5 version, python version, compilation flags...).

@avalentino I might be wrong, but I don't think the assert can be dropped; perhaps commenting this assert out and see if tests pass is certainly another option.

**Comment by keszybz** [comment]
> @keszybz do you have he possibility to investigate the problem on the s390x platform?

Unfortunately not. I can only build packages there ;(

**Comment by tomkooij** [comment]
Closed. Please reopen if access to s390x platform to test/fix.

**Comment by michelmno** [comment]
Same failure for ppc64 (BE) on openSUSE as reported in OBS (1) for version 3.6.1 with Traceback extracted from attached file.
```
[  726s] Traceback (most recent call last):
[  726s]   File "/home/abuild/rpmbuild/BUILDROOT/python-tables-3.6.1-2.2.ppc64/usr/lib64/python3.8/site-packages/tables/tests/test_index_backcompat.py", line 18, in setUp
[  726s]     self.sl = self.table1.cols.var1.index.slicesize
[  726s] AttributeError: 'UnImplemented' object has no attribute 'cols'
```
[python_tables_standard_ppc64_202008141516.log](https://github.com/PyTables/PyTables/files/5074957/python_tables_standard_ppc64_202008141516.log)

I have a local ppc64 guest, I could make some trials if that could help (I am not familiar with python)

(1) https://build.opensuse.org/package/show/devel:languages:python:numeric/python-tables
     https://build.opensuse.org/package/live_build_log/devel:languages:python:numeric/python-tables/openSUSE_Factory_PowerPC/ppc64

**Comment by keszybz** [comment]
The issue remain valid.
