### ISSUE TITLE
tables.exceptions.HDF5ExtError: Problems reading the index data in Last Row.

### ISSUE THREAD

**Issue by adamjstewart** [PyTables/PyTables#782]
I'm writing some ML/DL research code that uses a PyTorch data loader to read data from an HDF5 file through Pandas/PyTables. The HDF5 file in question is also written using Pandas/PyTables, but on a different machine. I create the file on my laptop, then transfer it to AWS for training. Here are the relevant specs:

### Laptop

- Python 3.7.4
- Pandas 0.25.1
- PyTables 3.6.0
- HDF5 1.10.5
- macOS 10.15.1 Catalina

### AWS

- Python 3.6.5
- Pandas 0.24.2
- PyTables 3.4.3
- HDF5 1.10.2
- Amazon Linux 2

### Error Message

Here is the full stack trace of the error message:
```
Traceback (most recent call last):
  File "./train.py", line 225, in <module>
    for batch, (data, labels) in enumerate(train_loader, 1):
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
tables.exceptions.HDF5ExtError: Caught HDF5ExtError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 257, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/ec2-user/crop_classification/datasets/hdf5.py", line 91, in __getitem__
    recent = self.store.select('cdl', where='YEAR=2018').iloc[idx]
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/pandas/io/pytables.py", line 740, in select
    return it.get_result()
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/pandas/io/pytables.py", line 1518, in get_result
    results = self.func(self.start, self.stop, where)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/pandas/io/pytables.py", line 733, in func
    columns=columns)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/pandas/io/pytables.py", line 4254, in read
    if not self.read_axes(where=where, **kwargs):
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/pandas/io/pytables.py", line 3444, in read_axes
    values = self.selection.select()
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/pandas/io/pytables.py", line 4850, in select
    stop=self.stop)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tables/table.py", line 1548, in read_where
    self._where(condition, condvars, start, stop, step)]
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tables/table.py", line 1515, in _where
    self, compiled, condition, condvars, start, stop, step)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tables/table.py", line 217, in _table__where_indexed
    chunkmap = index.get_chunkmap()
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tables/index.py", line 2037, in get_chunkmap
    self.indicesLR._read_index_slice(start, stop, idx)
  File "tables/indexesextension.pyx", line 1508, in tables.indexesextension.LastRowArray._read_index_slice
tables.exceptions.HDF5ExtError: Problems reading the index data in Last Row.
```

### Additional Information

For some reason, when I try a batch size of 1 (read a single row from the HDF5 file at a time), everything works fine. As soon as the batch size is greater than 1, things crash on AWS, but not on my laptop.

Is there some known incompatibility between these versions of PyTables/Pandas/HDF5 or with transfering HDF5 files between macOS and Linux? I can upload the HDF5 file in question if you want (it's around 800 MB). I can't share the full code as the research is unpublished yet, but if there are no obvious reasons for this bug I can try writing a minimal working example to reproduce the bug.

**Comment by tomkooij** [comment]
There shouldn't be any incompatibility between the versions/platforms you use.

Perphaps you can try to use pytables 3.4.3 on your MacOS laptop as well? 

If you have a minimal example that reads the file, I can download the file and test it on a local Linux box using PyTables 3.4.3 (with/without pandas)

**Comment by adamjstewart** [comment]
@tomkooij here is a smaller version of the file in question: [store.h5](https://github.com/PyTables/PyTables/files/3975428/store.txt) (had to change file extension to .txt to upload on GitHub).

The code to read the file is something like:
```python
import pandas as pd
x = pd.HDFStore('store.h5', mode='r')
x.select('cdl', when='YEAR=2018').iloc[0]  # crashes
```
I just discovered one other important clue. PyTorch data loaders allow you to specify how many workers are used to load the data in parallel. With 1 worker, things work fine on both my laptop and on AWS. With 2+ workers loading in parallel, things crash on AWS. So this is likely an issue specific to parallel access of HDF5 files.

I'll try creating the file with PyTables 3.4.3 on my laptop. I'll also try reading the file with PyTables 3.6.0 on AWS.

**Comment by adamjstewart** [comment]
Using PyTables 3.6.1, Pandas 0.25.1, PyTorch 1.3.1, and Python 3.7.4 on AWS seems to fix the issue. I'm not sure which of these libraries caused the error, but it seems to be fixed in the latest versions. Thanks for your help in debugging this!
