### ISSUE TITLE
Files cannot be opened when list of filters differ from when written and filters were supplied globally

### ISSUE THREAD

**Issue by MaxNoe** [PyTables/PyTables#811]
## Description

When `filters` is supplied globally when creating a new file using `open_file(..., filters=Filters(...)`, these files cannot be opened, if the   list of filters differes from the ones which which the file was created.

## Cause

When providing global `filters` for a file, an hdf5 attribute `FILTERS` is added to the root and each group in the file, containing the number obtained by calling `Filters._pack`. 

This number is parsed back with `Filters._unpack` every time this attribute is encountered.

When a file was created using 
```
filters=tables.Filters(complib='blosc:zstd', fletcher32=True, complevel=5)
```

using a build of tables/blosc that e.g. supports these 10 complibs:
```
['zlib', 'lzo', 'bzip2', 'blosc', 'blosc:blosclz', 'blosc:lz4', 'blosc:lz4hc', 'blosc:snappy', 'blosc:zlib', 'blosc:zstd']
```

and then read with a build of pytables / blosc that only supports these 9 complibs:
```
['zlib', 'lzo', 'bzip2', 'blosc', 'blosc:blosclz', 'blosc:lz4', 'blosc:lz4hc', 'blosc:zlib', 'blosc:zstd']
```

the error:
```
Traceback (most recent call last):
  File "read_test_file.py", line 12, in <module>
    with tables.open_file(path, mode='r') as f:
  File "/tmp/miniconda/lib/python3.7/site-packages/tables/file.py", line 315, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/tmp/miniconda/lib/python3.7/site-packages/tables/file.py", line 813, in __init__
    root._g_post_init_hook()
  File "/tmp/miniconda/lib/python3.7/site-packages/tables/group.py", line 259, in _g_post_init_hook
    if 'VERSION' in self._v_attrs._v_attrnamessys:
  File "/tmp/miniconda/lib/python3.7/site-packages/tables/utils.py", line 240, in newfget
    mydict[name] = value = fget(self)
  File "/tmp/miniconda/lib/python3.7/site-packages/tables/node.py", line 173, in _v_attrs
    return self._AttributeSet(self)
  File "/tmp/miniconda/lib/python3.7/site-packages/tables/attributeset.py", line 248, in __init__
    self.__getattr__(attr)
  File "/tmp/miniconda/lib/python3.7/site-packages/tables/attributeset.py", line 373, in __getattr__
    retval = Filters._unpack(value)
  File "/tmp/miniconda/lib/python3.7/site-packages/tables/filters.py", line 261, in _unpack
    % complib_id)
ValueError: invalid compression library id: 10
```

is raised.

The attribute `FILTERS` is not needed for reading the data.
If one uses h5py to remove all occurences of the `FILTER` attribute, `tables` is able to open the file and read the data.

So one possibility would be to just ignore the error in parsing `FILTERS` when encountering it when opening a file.

### Steps to reproduce

Currently, a fresh pip install supports the 10 levels including snappy but a fresh conda install only supports 9 complibs (all but snappy).

Create the file using:

```python
import tables
import tables.filters
import numpy as np

print(tables.__version__)
print(tables.filters.all_complibs)
print(tables.filters.blosc_compressor_list())
print(tables.filters.blosc_version)


class Table(tables.IsDescription):
    id = tables.Int64Col()
    value = tables.Float64Col()


filters = tables.Filters(complib='blosc:zstd', fletcher32=True, complevel=5)

print(filters._pack(), (filters._pack() >> 8) & 0xff)


with tables.open_file('./test_filters.h5', mode='w', filters=filters) as f:
    group = f.create_group('/', 'group')
    table = f.create_table(group, 'test', Table)

    for i in range(10):
        row = table.row
        row['id'] = i
        row['value'] = np.random.normal()
        row.append()
```

Read the file using: 

```python
import tables
import tables.filters

print(tables.__version__)
print(tables.filters.all_complibs)
print(tables.filters.blosc_compressor_list())
print(tables.filters.blosc_version)

tables.open_file('./test_filters.h5').root.group.test[:]
```

A tables/blosc combination with smaller number of filters is able to read it, as long as the used filter is present as soon as you remove the `FILTERS` attribute, e.g. using h5py:

```python

import h5py
import sys


def remove_filters(f):
    if 'FILTERS' in f.attrs:
        print('Removing filters from', f)
        del f.attrs['FILTERS']

    if hasattr(f, 'values'):
        for sub in f.values():
            remove_filters(sub)


def main():
    path = sys.argv[1]

    with h5py.File(path, mode='r+') as f:
        remove_filters(f)
```

**Comment by MaxNoe** [comment]
Could any maintainer at least comment on this? We are facing this issue with important data files.
It would be great if this issue could be addressed.

**Comment by FrancescAlted** [comment]
Yes, your diagnositic and PR #812 are correct.  I've just merged your PR.  Thank you and sorry for the incoveniences!
