### ISSUE TITLE
Doctests fail

### ISSUE THREAD

**Issue by avalentino** [PyTables/PyTables#874]
```
$ env PYTHONPATH=. python3 -m pytest --doctest-only tables
============================================================= test session starts =============================================================
platform linux -- Python 3.8.6, pytest-4.6.11, py-1.9.0, pluggy-0.13.0
rootdir: /home/antonio/projects/PyTables
plugins: remotedata-0.3.2, hypothesis-5.29.0, openfiles-0.5.0, flake8-1.0.6, arraydiff-0.3, filter-subpackage-0.1.1, astropy-header-0.1.2, cov-2.8.1, doctestplus-0.7.0, cython-0.1.0
collected 37 items                                                                                                                            

tables/atom.py .........                                                                                                                [ 24%]
tables/attributeset.py F                                                                                                                [ 27%]
tables/expression.py F                                                                                                                  [ 29%]
tables/file.py F                                                                                                                        [ 32%]
tables/filters.py ..                                                                                                                    [ 37%]
tables/group.py FF                                                                                                                      [ 43%]
tables/link.py FFFFF                                                                                                                    [ 56%]
tables/path.py ....                                                                                                                     [ 67%]
tables/table.py F                                                                                                                       [ 70%]
tables/utils.py F                                                                                                                       [ 72%]
tables/misc/enum.py ..........                                                                                                          [100%]

================================================================== FAILURES ===================================================================
_________________________________________________ [doctest] tables.attributeset.AttributeSet __________________________________________________
112         >>> import os, tempfile
113         >>> import tables as tb
114         >>>
115         >>> class MyClass(object):
116         ...   foo = 'bar'
117         ...
118         >>> myObject = MyClass()  # save object of custom class in HDF5 attr
119         >>> h5fname = tempfile.mktemp(suffix='.h5')
120         >>> h5f = tb.open_file(h5fname, 'w')
121         >>> h5f.root._v_attrs.obj = myObject  # store the object
UNEXPECTED EXCEPTION: PicklingError("Can't pickle <class 'tables.attributeset.MyClass'>: attribute lookup MyClass on tables.attributeset failed")
Traceback (most recent call last):

  File "/usr/lib/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",

  File "<doctest tables.attributeset.AttributeSet[6]>", line 1, in <module>

  File "/home/antonio/projects/PyTables/tables/attributeset.py", line 488, in __setattr__
    self._g__setattr(name, value)

  File "/home/antonio/projects/PyTables/tables/attributeset.py", line 430, in _g__setattr
    self._g_setattr(self._v_node, name, stvalue)

  File "tables/hdf5extension.pyx", line 706, in tables.hdf5extension.AttributeSet._g_setattr
    value = pickle.dumps(value, 0)

_pickle.PicklingError: Can't pickle <class 'tables.attributeset.MyClass'>: attribute lookup MyClass on tables.attributeset failed

/home/antonio/projects/PyTables/tables/attributeset.py:121: UnexpectedException
______________________________________________________ [doctest] tables.expression.Expr _______________________________________________________
064     kwargs : dict
065         This is meant to pass additional parameters to the Numexpr kernel.
066         This is basically the same as the kwargs argument in
067         Numexpr.evaluate(), and is mainly meant for advanced use.
068 
069     Examples
070     --------
071     The following shows an example of using Expr.
072 
073         >>> a = f.create_array('/', 'a', np.array([1,2,3]))
UNEXPECTED EXCEPTION: NameError("name 'f' is not defined")
Traceback (most recent call last):

  File "/usr/lib/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",

  File "<doctest tables.expression.Expr[0]>", line 1, in <module>

NameError: name 'f' is not defined

/home/antonio/projects/PyTables/tables/expression.py:73: UnexpectedException
_____________________________________________________ [doctest] tables.file.File.__str__ ______________________________________________________
2712 Return a short string representation of the object tree.
2713 
2714         Examples
2715         --------
2716 
2717         ::
2718 
2719             >>> f = tables.open_file('data/test.h5')
UNEXPECTED EXCEPTION: NameError("name 'tables' is not defined")
Traceback (most recent call last):

  File "/usr/lib/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",

  File "<doctest tables.file.File.__str__[0]>", line 1, in <module>

NameError: name 'tables' is not defined

/home/antonio/projects/PyTables/tables/file.py:2719: UnexpectedException
____________________________________________________ [doctest] tables.group.Group.__repr__ ____________________________________________________
042 Return a detailed string representation of the group.
043 
044         Examples
045         --------
046 
047         ::
048 
049             >>> f = tables.open_file('data/test.h5')
UNEXPECTED EXCEPTION: NameError("name 'tables' is not defined")
Traceback (most recent call last):

  File "/usr/lib/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",

  File "<doctest tables.group.Group.__repr__[0]>", line 1, in <module>

NameError: name 'tables' is not defined

/home/antonio/projects/PyTables/tables/group.py:49: UnexpectedException
____________________________________________________ [doctest] tables.group.Group.__str__ _____________________________________________________
042 Return a short string representation of the group.
043 
044         Examples
045         --------
046 
047         ::
048 
049             >>> f=tables.open_file('data/test.h5')
UNEXPECTED EXCEPTION: NameError("name 'tables' is not defined")
Traceback (most recent call last):

  File "/usr/lib/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",

  File "<doctest tables.group.Group.__str__[0]>", line 1, in <module>

NameError: name 'tables' is not defined

/home/antonio/projects/PyTables/tables/group.py:49: UnexpectedException
_________________________________________________ [doctest] tables.link.ExternalLink.__call__ _________________________________________________
351         You can pass all the arguments supported by the :func:`open_file`
352         function (except filename, of course) so as to open the referenced
353         external file.
354 
355         Examples
356         --------
357 
358         ::
359 
360             >>> f=tb.open_file('data1/test1.h5')
UNEXPECTED EXCEPTION: OSError('``/home/antonio/projects/PyTables/data1/test1.h5`` does not exist')
Traceback (most recent call last):

  File "/usr/lib/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",

  File "<doctest tables.link.ExternalLink.__call__[0]>", line 1, in <module>

  File "/home/antonio/projects/PyTables/tables/file.py", line 309, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)

  File "/home/antonio/projects/PyTables/tables/file.py", line 772, in __init__
    self._g_new(filename, mode, **params)

  File "tables/hdf5extension.pyx", line 367, in tables.hdf5extension.File._g_new
    check_file_access(name, pymode)

  File "/home/antonio/projects/PyTables/tables/utils.py", line 153, in check_file_access
    raise OSError(f"``{path}`` does not exist")

OSError: ``/home/antonio/projects/PyTables/data1/test1.h5`` does not exist

/home/antonio/projects/PyTables/tables/link.py:360: UnexpectedException
_________________________________________________ [doctest] tables.link.ExternalLink.__str__ __________________________________________________
045 Return a short string representation of the link.
046 
047         Examples
048         --------
049 
050         ::
051 
052             >>> f=tb.open_file('data1/test1.h5')
UNEXPECTED EXCEPTION: OSError('``/home/antonio/projects/PyTables/data1/test1.h5`` does not exist')
Traceback (most recent call last):

  File "/usr/lib/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",

  File "<doctest tables.link.ExternalLink.__str__[0]>", line 1, in <module>

  File "/home/antonio/projects/PyTables/tables/file.py", line 309, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)

  File "/home/antonio/projects/PyTables/tables/file.py", line 772, in __init__
    self._g_new(filename, mode, **params)

  File "tables/hdf5extension.pyx", line 367, in tables.hdf5extension.File._g_new
    check_file_access(name, pymode)

  File "/home/antonio/projects/PyTables/tables/utils.py", line 153, in check_file_access
    raise OSError(f"``{path}`` does not exist")

OSError: ``/home/antonio/projects/PyTables/data1/test1.h5`` does not exist

/home/antonio/projects/PyTables/tables/link.py:52: UnexpectedException
_______________________________________________________ [doctest] tables.link.SoftLink ________________________________________________________
159     via the `__call__()` special method (this action is called *dereferencing*;
160     see below)
161 
162     Examples
163     --------
164 
165     ::
166 
167         >>> f = tb.open_file('/tmp/test_softlink.h5', 'w')
168         >>> a = f.create_array('/', 'A', np.arange(10))
UNEXPECTED EXCEPTION: NameError("name 'np' is not defined")
Traceback (most recent call last):

  File "/usr/lib/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",

  File "<doctest tables.link.SoftLink[1]>", line 1, in <module>

NameError: name 'np' is not defined

/home/antonio/projects/PyTables/tables/link.py:168: UnexpectedException
___________________________________________________ [doctest] tables.link.SoftLink.__call__ ___________________________________________________
201 Dereference `self.target` and return the object.
202 
203         Examples
204         --------
205 
206         ::
207 
208             >>> f=tb.open_file('data/test.h5')
UNEXPECTED EXCEPTION: OSError('``/home/antonio/projects/PyTables/data/test.h5`` does not exist')
Traceback (most recent call last):

  File "/usr/lib/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",

  File "<doctest tables.link.SoftLink.__call__[0]>", line 1, in <module>

  File "/home/antonio/projects/PyTables/tables/file.py", line 309, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)

  File "/home/antonio/projects/PyTables/tables/file.py", line 772, in __init__
    self._g_new(filename, mode, **params)

  File "tables/hdf5extension.pyx", line 367, in tables.hdf5extension.File._g_new
    check_file_access(name, pymode)

  File "/home/antonio/projects/PyTables/tables/utils.py", line 153, in check_file_access
    raise OSError(f"``{path}`` does not exist")

OSError: ``/home/antonio/projects/PyTables/data/test.h5`` does not exist

/home/antonio/projects/PyTables/tables/link.py:208: UnexpectedException
___________________________________________________ [doctest] tables.link.SoftLink.__str__ ____________________________________________________
045 Return a short string representation of the link.
046 
047         Examples
048         --------
049 
050         ::
051 
052             >>> f=tb.open_file('data/test.h5')
UNEXPECTED EXCEPTION: OSError('``/home/antonio/projects/PyTables/data/test.h5`` does not exist')
Traceback (most recent call last):

  File "/usr/lib/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",

  File "<doctest tables.link.SoftLink.__str__[0]>", line 1, in <module>

  File "/home/antonio/projects/PyTables/tables/file.py", line 309, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)

  File "/home/antonio/projects/PyTables/tables/file.py", line 772, in __init__
    self._g_new(filename, mode, **params)

  File "tables/hdf5extension.pyx", line 367, in tables.hdf5extension.File._g_new
    check_file_access(name, pymode)

  File "/home/antonio/projects/PyTables/tables/utils.py", line 153, in check_file_access
    raise OSError(f"``{path}`` does not exist")

OSError: ``/home/antonio/projects/PyTables/data/test.h5`` does not exist

/home/antonio/projects/PyTables/tables/link.py:52: UnexpectedException
_____________________________________________________ [doctest] tables.table.Table.where ______________________________________________________
1428             use methods that can change the number of rows in the table
1429             (like :meth:`Table.append` or :meth:`Table.remove_rows`) or
1430             unexpected errors will happen.
1431 
1432         Examples
1433         --------
1434 
1435         ::
1436 
1437             >>> passvalues = [ row['col3'] for row in
UNEXPECTED EXCEPTION: NameError("name 'table' is not defined")
Traceback (most recent call last):

  File "/usr/lib/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",

  File "<doctest tables.table.Table.where[0]>", line 2, in <module>

NameError: name 'table' is not defined

/home/antonio/projects/PyTables/tables/table.py:1437: UnexpectedException
_______________________________________________________ [doctest] tables.utils.lazyattr _______________________________________________________
194     itself.  For instance:
195 
196     >>> class MyClass(object):
197     ...     @lazyattr
198     ...     def attribute(self):
199     ...         'Attribute description.'
200     ...         print('creating value')
201     ...         return 10
202     ...
203     >>> type(MyClass.attribute)
Expected:
    <type 'property'>
Got:
    <class 'property'>

/home/antonio/projects/PyTables/tables/utils.py:203: DocTestFailure
============================================================== warnings summary ===============================================================
tables/path.py::tables.path.check_attribute_name
  <doctest tables.path.check_attribute_name[2]>:1: NaturalNameWarning: object name is not a valid Python identifier: 'a:b'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though

tables/path.py::tables.path.check_attribute_name
  <doctest tables.path.check_attribute_name[3]>:1: NaturalNameWarning: object name is not a valid Python identifier: '/a/b'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though

tables/path.py::tables.path.check_attribute_name
  <doctest tables.path.check_attribute_name[4]>:1: NaturalNameWarning: object name is not a valid Python identifier: '/'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though

tables/path.py::tables.path.check_attribute_name
  <doctest tables.path.check_attribute_name[5]>:1: NaturalNameWarning: object name is not a valid Python identifier: '.'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though

tables/path.py::tables.path.check_name_validity
  /home/antonio/projects/PyTables/tables/path.py:154: NaturalNameWarning: object name is not a valid Python identifier: 'a:b'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
    check_attribute_name(name)

tables/path.py::tables.path.check_name_validity
  /home/antonio/projects/PyTables/tables/path.py:154: NaturalNameWarning: object name is not a valid Python identifier: '/a/b'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
    check_attribute_name(name)

tables/path.py::tables.path.check_name_validity
  /home/antonio/projects/PyTables/tables/path.py:154: NaturalNameWarning: object name is not a valid Python identifier: '.'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
    check_attribute_name(name)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================================== 12 failed, 25 passed, 7 warnings in 1.34 seconds ===============================================
Closing remaining open files:/tmp/test_softlink.h5...done/tmp/tmpg3offh16.h5...done
```

**Comment by eumiro** [comment]
Oh, we do not have doctest in GHA CI. You installed `pytest-doctestplus`, right?

**Comment by avalentino** [comment]
Yes I have doctestplus installed but probably it is not strictly necessary

**Comment by avalentino** [comment]
All doctests except one are now fixed.
The remaining one cannot work as a doctest because it pickles an instance of a class that has not been defined art toplevel.

Doctests shall be executed as follows:

```
$ env PYTHONPATH=. python3 -m pytest --doctest-only tables -k "not AttributeSet"
```
