### ISSUE TITLE
How to avoid: H5FD_lock, 'Resource temporarily unavailable'

### ISSUE THREAD

**Issue by jondoesntgit** [PyTables/PyTables#888]
I open up two terminals, and I run this in the first one:

Possibly related to https://github.com/h5py/h5py/issues/1101

```
>>> import tables as pt
>>> h5f = pt.open_file('foo.h5', 'w')
```

```
>>> import tables as pt
>>> h5f = pt.open_file('foo.h5', 'r')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.7/site-packages/tables/file.py", line 315, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/tables/file.py", line 778, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 509, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1567, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1640, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 959, in H5FD_sec2_lock
    unable to lock file, errno = 35, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace
```

**Comment by jondoesntgit** [comment]
Figured it out, and wanted to put the solution here for others.

If you add the following to your `.bashrc` file, then you can avoid this problem.

```
HDF5_USE_FILE_LOCKING=FALSE
```

**Comment by avalentino** [comment]
@jondoesntgit thanks for the hint
