### ISSUE TITLE
Where clauses containing arithmetic operators are handled incorrectly

### ISSUE THREAD

**Issue by Traderjoe95** [PyTables/PyTables#895]
I am trying to use arithmetic operations inside a `where` clause to select rows from a table stored via the `pandas.HDFStore` class. My concrete example would be something like `(A % 3) == 0`. Unfortunately, this kind of conditions does not seem to be possible in the current implementation, although https://www.pytables.org/usersguide/condition_syntax.html seems to suggest otherwise.

I have tracked down the issue to PyTables, which is why I opened the issue in this repository instead of `pandas`. The condition was passed through to PyTables unaltered, but then PyTables tries to interpret `A % 3` as a boolean expression, which it obviously isn't.

## My Environment
CPython 3.8
PyTables 3.6.1
numexpr 2.7.3

## Reproducer

```python
import numpy as np
import pandas as pd

df = pd.DataFrame({'A': np.arange(0, 10)})

with pd.HDFStore('test.h5') as s:
    s.put("test", df, format='t', data_columns=['A'])

    print(s.select("test", where=["(A % 3) == 0"])
```

### Expected Behavior
A dataframe containing only rows 0, 3, 6, 9 is printed

### Actual Behavior
The condition fails to parse:

```
Traceback (most recent call last):
  File "C:\Python38\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "D:\Studies\14 Master Thesis\Project\.venv\lib\site-packages\pandas\io\pytables.py", line 845, in select
    return it.get_result()
  File "D:\Studies\14 Master Thesis\Project\.venv\lib\site-packages\pandas\io\pytables.py", line 1913, in get_result
    results = self.func(self.start, self.stop, where)
  File "D:\Studies\14 Master Thesis\Project\.venv\lib\site-packages\pandas\io\pytables.py", line 829, in func
    return s.read(start=_start, stop=_stop, where=_where, columns=columns)
  File "D:\Studies\14 Master Thesis\Project\.venv\lib\site-packages\pandas\io\pytables.py", line 4458, in read
    result = self._read_axes(where=where, start=start, stop=stop)
  File "D:\Studies\14 Master Thesis\Project\.venv\lib\site-packages\pandas\io\pytables.py", line 3662, in _read_axes
    values = selection.select()
  File "D:\Studies\14 Master Thesis\Project\.venv\lib\site-packages\pandas\io\pytables.py", line 5179, in select
    return self.table.table.read_where(
  File "D:\Studies\14 Master Thesis\Project\.venv\lib\site-packages\tables\table.py", line 1542, in read_where
    self._where(condition, condvars, start, stop, step)]
  File "D:\Studies\14 Master Thesis\Project\.venv\lib\site-packages\tables\table.py", line 1504, in _where
    compiled = self._compile_condition(condition, condvars)
  File "D:\Studies\14 Master Thesis\Project\.venv\lib\site-packages\tables\table.py", line 1359, in _compile_condition
    compiled = compile_condition(condition, typemap, indexedcols)
  File "D:\Studies\14 Master Thesis\Project\.venv\lib\site-packages\tables\conditions.py", line 411, in compile_condition
    raise TypeError("condition ``%s`` does not have a boolean type"
TypeError: condition ``(A % 3)`` does not have a boolean type
```

**Comment by Traderjoe95** [comment]
Well, apparently I didn't quite look at the right place, this seems to be a pandas issue. My bad.
