### ISSUE TITLE
Why do you try to write the source file when backing up?

### ISSUE THREAD

**Issue by linzhanyu** [PyTables/PyTables#910]
Traceback (most recent call last):
  File "/mnt/disk/stock/finance-dev/Core/MachineLearn/ModelDef.py", line 148, in _EntryX
    self.Start()
  File "/mnt/disk/stock/finance-dev/Core/MachineLearn/ModelDef.py", line 180, in Start
    self.OnStart()
  File "/mnt/disk/stock/finance-dev/Core/MachineLearn/TemplateCheck.py", line 21, in OnStart
    self.Analysis()
  File "/mnt/disk/stock/finance-dev/Core/MachineLearn/HDF5Backup.py", line 30, in Analysis
    main()
  File "/usr/local/lib/python3.8/site-packages/tables/scripts/ptrepack.py", line 529, in main
    copy_children(
  File "/usr/local/lib/python3.8/site-packages/tables/scripts/ptrepack.py", line 270, in copy_children
    srcfileh.close()
  File "/usr/local/lib/python3.8/site-packages/tables/file.py", line 2723, in close
    self.root._f_close()
  File "/usr/local/lib/python3.8/site-packages/tables/group.py", line 933, in _f_close
    self._g_close_descendents()
  File "/usr/local/lib/python3.8/site-packages/tables/group.py", line 897, in _g_close_descendents
    node_manager.close_subtree(self._v_pathname)
  File "/usr/local/lib/python3.8/site-packages/tables/file.py", line 538, in close_subtree
    self._close_nodes(paths, cache.pop)
  File "/usr/local/lib/python3.8/site-packages/tables/file.py", line 513, in _close_nodes
    node._f_close()
  File "/usr/local/lib/python3.8/site-packages/tables/table.py", line 2961, in _f_close
    self.flush()
  File "/usr/local/lib/python3.8/site-packages/tables/table.py", line 2898, in flush
    rowsadded = self.flush_rows_to_index(_lastrow=True)
  File "/usr/local/lib/python3.8/site-packages/tables/table.py", line 2521, in flush_rows_to_index
    rowsadded = self._add_rows_to_index(
  File "/usr/local/lib/python3.8/site-packages/tables/table.py", line 2550, in _add_rows_to_index
    index.append_last_row(
  File "/usr/local/lib/python3.8/site-packages/tables/index.py", line 741, in append_last_row
    sortedLR.attrs.nelements = nelementsSLR
  File "/usr/local/lib/python3.8/site-packages/tables/attributeset.py", line 466, in __setattr__
    nodefile._check_writable()
  File "/usr/local/lib/python3.8/site-packages/tables/file.py", line 2167, in _check_writable
    raise FileModeError("the file is not writable : %s" % (self.mode, ) )
tables.exceptions.FileModeError: the file is not writable : r

**Comment by avalentino** [comment]
Hi @linzhanyu thanks for reporting.
Could you please provide more information and, possibly, a small code example to reproduce the issue?

**Comment by avalentino** [comment]
Fixed by #914
