### ISSUE TITLE
creating vlarray with fletcher32 filter fails in pytables 3.7.0

### ISSUE THREAD

**Issue by alpae** [PyTables/PyTables#935]
Hi, 

with the new release of pytables the creation of a vlarray with an activated fletcher32 filter fails within the HDF library. Here's a minimal script that shows this behavior:

```
import tables
import numpy

tables.print_versions()

d = numpy.array([(x, "Test{:02d}".format(x).encode('utf-8')) for x in range(0, 100)],
                dtype=[('A', 'i4'), ('B', 'S10')])

with tables.open_file('test.h5', 'w',
                      filters=tables.Filters(complevel=6, complib="blosc", shuffle=True, fletcher32=True,)
                      ) as h5:
    h5.create_table('/', 'test', obj=d)
    a = h5.create_vlarray('/', 'arr', atom=tables.ObjectAtom())
    a.append(d)

with tables.open_file('test.h5', 'r') as h5:
    res = h5.root.test[:]
    o = h5.root.arr[-1]


numpy.testing.assert_array_equal(res, d)
numpy.testing.assert_array_equal(o, d)
```
And here's the output:
```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.7.0
HDF5 version:        1.12.1
NumPy version:       1.22.0
Numexpr version:     2.8.1 (not using Intel's VML/MKL)
Zlib version:        1.2.11 (in Python interpreter)
LZO version:         2.10 (Mar 01 2017)
BZIP2 version:       1.0.6 (6-Sept-2010)
Blosc version:       1.21.1 (2021-10-06)
Blosc compressors:   blosclz (2.5.1), lz4 (1.9.3), lz4hc (1.9.3), zlib (1.2.11), zstd (1.5.0)
Blosc filters:       shuffle, bitshuffle
Python version:      3.8.8 (default, Mar 12 2021, 13:20:21)
[Clang 11.0.0 (clang-1100.0.33.17)]
Platform:            macOS-10.14.6-x86_64-i386-64bit
Byte-ordering:       little
Detected cores:      4
Default encoding:    utf-8
Default FS encoding: utf-8
Default locale:      (en_US, UTF-8)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Traceback (most recent call last):
  File "bug.py", line 18, in <module>
    a = h5.create_vlarray('/', 'arr', atom=tables.ObjectAtom())
  File "/Users/adriaal/.local/share/virtualenvs/tables_bug-D7M0yWtK/lib/python3.8/site-packages/tables/file.py", line 1463, in create_vlarray
    ptobj = VLArray(parentnode, name,
  File "/Users/adriaal/.local/share/virtualenvs/tables_bug-D7M0yWtK/lib/python3.8/site-packages/tables/vlarray.py", line 334, in __init__
    super().__init__(parentnode, name, new, filters,
  File "/Users/adriaal/.local/share/virtualenvs/tables_bug-D7M0yWtK/lib/python3.8/site-packages/tables/leaf.py", line 259, in __init__
    super().__init__(parentnode, name, _log)
  File "/Users/adriaal/.local/share/virtualenvs/tables_bug-D7M0yWtK/lib/python3.8/site-packages/tables/node.py", line 249, in __init__
    self._v_objectid = self._g_create()
  File "/Users/adriaal/.local/share/virtualenvs/tables_bug-D7M0yWtK/lib/python3.8/site-packages/tables/vlarray.py", line 404, in _g_create
    self._v_objectid = self._create_array(self._v_new_title)
  File "tables/hdf5extension.pyx", line 1970, in tables.hdf5extension.VLArray._create_array
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5D.c", line 141, in H5Dcreate2
    unable to create dataset
  File "H5VLcallback.c", line 1806, in H5VL_dataset_create
    dataset create failed
  File "H5VLcallback.c", line 1771, in H5VL__dataset_create
    dataset create failed
  File "H5VLnative_dataset.c", line 73, in H5VL__native_dataset_create
    unable to create dataset
  File "H5Dint.c", line 396, in H5D__create_named
    unable to create and link to dataset
  File "H5L.c", line 1767, in H5L_link_object
    unable to create new link to object
  File "H5L.c", line 2009, in H5L__create_real
    can't insert link
  File "H5Gtraverse.c", line 837, in H5G_traverse
    internal path traversal failed
  File "H5Gtraverse.c", line 613, in H5G__traverse_real
    traversal operator failed
  File "H5L.c", line 1815, in H5L__link_cb
    unable to create object
  File "H5Oint.c", line 2468, in H5O_obj_create
    unable to open object
  File "H5Doh.c", line 289, in H5O__dset_create
    unable to create dataset
  File "H5Dint.c", line 1282, in H5D__create
    H5Z_has_optional_filter() failed
  File "H5Z.c", line 1044, in H5Z_ignore_filters
    not suitable for filters

End of HDF5 error back trace

Problems creating the VLArray.
```

when the fletcher32 filter is deactivated, the script runs fine, and so does it with pytables==3.6.1 (on python3.8).

on python3.9 also pytables==3.6.1 seems to fail in the same way (but there's a difference in the hdf library used between 3.8 and 3.9): 1.10.5 vs 1.12.1.

**Comment by avalentino** [comment]
@alpae unfortunately it seems that it is no longer possible to use the fletcher32 filter on vlen strings with recent versions of the HDF5 library (see also https://github.com/h5py/h5py/issues/1948#issuecomment-925707191).

Closing.
