### ISSUE TITLE
HDF5 version problems (Invalid version)

### ISSUE THREAD

**Issue by fumoffu947** [PyTables/PyTables#940]
Hi,

I am trying to install and use pytables, but I encounter a small problem with HDF5.
I have followed the installation recommendation:
```sudo apt-get install libhdf5-serial-dev```
Which is version 1.10.0-patch1.

Then install tables:
```python3 -m pip install tables```
```
Collecting tables
  Using cached ...
Collecting numexpr>=2.6.2 (from tables)
  Downloading ...
    100% |████████████████████████████████| 102kB 709kB/s
Collecting numpy>=1.19.0 (from tables)
  Downloading ...
    100% |████████████████████████████████| 11.4MB 218kB/s
Collecting packaging (from tables)
  Downloading ...
    100% |████████████████████████████████| 40kB 943kB/s
Collecting pyparsing!=3.0.5,>=2.0.2 (from packaging->tables)
  Downloading ...
    100% |████████████████████████████████| 102kB 1.1MB/s
Building wheels for collected packages: tables, numexpr, numpy
  Running setup.py bdist_wheel for tables ... done
  Stored in directory: /home/.../.cache/pip/wheels/1c/6f/2b/...
  Running setup.py bdist_wheel for numexpr ... done
  Stored in directory: /home/.../.cache/pip/wheels/d8/14/d3/...
  Running setup.py bdist_wheel for numpy ... done
  Stored in directory: /home/.../.cache/pip/wheels/7f/2f/9a/...
Successfully built tables numexpr numpy
Installing collected packages: numpy, pyparsing, packaging, numexpr, tables
Successfully installed numexpr-2.8.1 numpy-1.22.2 packaging-21.3 pyparsing-3.0.7 tables-3.7.0
```

Then wen running the tests it fails with:
```
$ python3.8 -m tables.test.test_all
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/.../.local/lib/python3.8/site-packages/tables/__init__.py", line 53, in <module>
    from .tests import print_versions, test
  File "/home/.../.local/lib/python3.8/site-packages/tables/tests/__init__.py", line 9, in <module>
    from tables.tests.common import print_versions
  File "/home/.../.local/lib/python3.8/site-packages/tables/tests/common.py", line 20, in <module>
    hdf5_version = Version(tb.hdf5_version)
  File "/home/.../.local/lib/python3.8/site-packages/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '1.10.0-patch1'
```

As it says to have at least the version 1.8.4 for HDF5, I guess this should work. What is wrong? (it it really necessary for me to try and install a earlier version of HDF5??)

**Comment by avalentino** [comment]
@fumoffu947 thanks for reporting

**Comment by fumoffu947** [comment]
Is there a quick fix for this? (or is there a problem with the 1.10.0-patch1 version of HDF5?)

**Comment by avalentino** [comment]
@fumoffu947 sorry I have not had time to look closely into it.

Probably a quick fix is possible just using the `packaging.version.LegacyVersion` as a fallback of `packaging.version.Version` in case of problems in the `tables/tests/common.py` file.

A PR would be very appreciated.

**Comment by fumoffu947** [comment]
Will see if I can find the time to fix it, but no promises 😄 
Thanks for the quick reply (know that people have their own work and such)
