### ISSUE TITLE
tests.test_basics.ThreadingTestCase and tests.test_expression.FunctionsTestCase fails on x86_64

### ISSUE THREAD

**Issue by hrnciar** [PyTables/PyTables#946]
Hello, I've tried to update Tables in Fedora to the latest released version 3.7.0, but I am getting test failures on x86_64 (other architectures build fine [0]). The tests.test_expression.FunctionsTestCase is also failing on x86_64 architecture in 3.6.1 which is the current version in Fedora [1]. See [2] for the full log. Can you help me? Thank you.
~~~~
======================================================================
FAIL: None (tables.tests.test_basics.ThreadingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/python-tables-3.7.0-2.fc37.x86_64/usr/lib64/python3.10/site-packages/tables/tests/test_basics.py", line 1403, in test
    self.assertEqual(q.get(), 'OK')
AssertionError: (<class 'tables.exceptions.HDF5ExtError'>[84 chars]a80>) != 'OK'
======================================================================
FAIL: None (tables.tests.test_expression.FunctionsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/python-tables-3.7.0-2.fc37.x86_64/usr/lib64/python3.10/site-packages/tables/tests/test_expression.py", line 898, in test00_simple
    self.assertTrue(common.areArraysEqual(r1, r2),
AssertionError: False is not true : Evaluate is returning a wrong value.
----------------------------------------------------------------------
~~~~
[0] https://koji.fedoraproject.org/koji/taskinfo?taskID=84634199
[1] https://koschei.fedoraproject.org/package/python-tables
[2] https://kojipkgs.fedoraproject.org//work/tasks/4262/84634262/build.log

**Comment by avalentino** [comment]
The issue in `test_expression` has been already fixed in master: https://github.com/PyTables/PyTables/commit/f3bfb0cc2508cd25e29408e25c8a06b211dd27e7.

Sorry, I'm not able to reproduce the issue with `tables.tests.test_basics.ThreadingTestCase`.

Is there a docker image that I can use to replicate your environment?

**Comment by hrnciar** [comment]
Tables were updated in Fedora during the weekend and it seems like the `tables.tests.test_basics.ThreadingTestCase` isn't a problem. The only skipped test was the `test_expression`. I think we can close this. 

[0] https://src.fedoraproject.org/rpms/python-tables/c/0279418d7f42e6ac22b58fc85a94cfde9c55a79a?branch=rawhide

**Comment by avalentino** [comment]
Thanks @hrnciar
