### ISSUE TITLE
'UnImplemented' object has no attribute 'cols' with Python 3.9 on PPC and s390x

### ISSUE THREAD

**Issue by skriesch** [PyTables/PyTables#951]
We are building PyTables for all architectures on openSUSE.
Build information:
[  314s] PyTables version:    3.7.0
[  314s] HDF5 version:        1.10.8
[  314s] NumPy version:       1.21.4
[  314s] Numexpr version:     2.8.1 (not using Intel's VML/MKL)
[  314s] Zlib version:        1.2.11 (in Python interpreter)
[  314s] LZO version:         2.10 (Mar 01 2017)
[  314s] BZIP2 version:       1.0.8 (13-Jul-2019)
[  314s] Blosc version:       1.21.1 (2021-10-06)
[  314s] Blosc compressors:   blosclz (2.5.1), lz4 (1.9.3), lz4hc (1.9.3), snappy (unknown), zlib (1.2.11), zstd (1.5.1)
[  314s] Blosc filters:       shuffle, bitshuffle
[  314s] Cython version:      0.29.28
[  314s] Python version:      3.9.12 (main, Mar 26 2022, 22:43:49) [GCC]
[  314s] Platform:            Linux-5.17.2-1-default-s390x-with-glibc2.35
[  314s] Byte-ordering:       big
[  314s] Detected cores:      2
[  314s] Default encoding:    utf-8
[  314s] Default FS encoding: utf-8
[  314s] Default locale:      (en_US, UTF-8)

The builds are failing for PPC and s390x with the following error message:

/abuild/rpmbuild/BUILDROOT/python-tables-3.7.0-2.1.s390x/usr/lib64/python3.9/site-packages/tables/group.py:1160: UserWarning: problems loading leaf ``/table1``::
[  700s] 
[  700s]   Wrong slicesize
[  700s] 
[  700s] The leaf will become an ``UnImplemented`` node.
[  700s]   warnings.warn(
[  701s] EEEEEEEEEE...............................................
[  701s] ======================================================================
[  701s] ERROR: test00_version (tables.tests.test_index_backcompat.Indexes2_0TestCase)
[  701s] Checking index version.
[  701s] ----------------------------------------------------------------------
[  701s] Traceback (most recent call last):
[  701s]   File "/home/abuild/rpmbuild/BUILDROOT/python-tables-3.7.0-2.1.s390x/usr/lib64/python3.9/site-packages/tables/tests/test_index_backcompat.py", line 12, in setUp
[  701s]     self.sl = self.table1.cols.var1.index.slicesize
[  701s] AttributeError: 'UnImplemented' object has no attribute 'cols'
[  701s] 
[  701s] ======================================================================
[  701s] ERROR: test01_string (tables.tests.test_index_backcompat.Indexes2_0TestCase)
[  701s] Checking string indexes.
[  701s] ----------------------------------------------------------------------
[  701s] Traceback (most recent call last):
[  701s]   File "/home/abuild/rpmbuild/BUILDROOT/python-tables-3.7.0-2.1.s390x/usr/lib64/python3.9/site-packages/tables/tests/test_index_backcompat.py", line 12, in setUp
[  701s]     self.sl = self.table1.cols.var1.index.slicesize
[  701s] AttributeError: 'UnImplemented' object has no attribute 'cols'
[  701s] 
[  701s] ======================================================================
[  701s] ERROR: test02_bool (tables.tests.test_index_backcompat.Indexes2_0TestCase)
[  701s] Checking bool indexes.
[  701s] ----------------------------------------------------------------------
[  701s] Traceback (most recent call last):
[  701s]   File "/home/abuild/rpmbuild/BUILDROOT/python-tables-3.7.0-2.1.s390x/usr/lib64/python3.9/site-packages/tables/tests/test_index_backcompat.py", line 12, in setUp
[  701s]     self.sl = self.table1.cols.var1.index.slicesize
[  701s] AttributeError: 'UnImplemented' object has no attribute 'cols'
[  701s] 
[  701s] ======================================================================
[  701s] ERROR: test03_int (tables.tests.test_index_backcompat.Indexes2_0TestCase)
[  701s] Checking int indexes.
[  701s] ----------------------------------------------------------------------
[  701s] Traceback (most recent call last):
[  701s]   File "/home/abuild/rpmbuild/BUILDROOT/python-tables-3.7.0-2.1.s390x/usr/lib64/python3.9/site-packages/tables/tests/test_index_backcompat.py", line 12, in setUp
[  701s]     self.sl = self.table1.cols.var1.index.slicesize
[  701s] AttributeError: 'UnImplemented' object has no attribute 'cols'
[  701s] 
[  701s] ======================================================================
[  701s] ERROR: test04_float (tables.tests.test_index_backcompat.Indexes2_0TestCase)
[  701s] Checking float indexes.
[  701s] ----------------------------------------------------------------------
[  701s] Traceback (most recent call last):
[  701s]   File "/home/abuild/rpmbuild/BUILDROOT/python-tables-3.7.0-2.1.s390x/usr/lib64/python3.9/site-packages/tables/tests/test_index_backcompat.py", line 12, in setUp
[  701s]     self.sl = self.table1.cols.var1.index.slicesize
[  701s] AttributeError: 'UnImplemented' object has no attribute 'cols'
[  701s] 
[  701s] ======================================================================
[  701s] ERROR: test00_version (tables.tests.test_index_backcompat.Indexes2_1TestCase)
[  701s] Checking index version.
[  701s] ----------------------------------------------------------------------
[  701s] Traceback (most recent call last):
[  701s]   File "/home/abuild/rpmbuild/BUILDROOT/python-tables-3.7.0-2.1.s390x/usr/lib64/python3.9/site-packages/tables/tests/test_index_backcompat.py", line 12, in setUp
[  701s]     self.sl = self.table1.cols.var1.index.slicesize
[  701s] AttributeError: 'UnImplemented' object has no attribute 'cols'
[  701s] 
[  701s] ======================================================================
[  701s] ERROR: test01_string (tables.tests.test_index_backcompat.Indexes2_1TestCase)
[  701s] Checking string indexes.
[  701s] ----------------------------------------------------------------------
[  701s] Traceback (most recent call last):
[  701s]   File "/home/abuild/rpmbuild/BUILDROOT/python-tables-3.7.0-2.1.s390x/usr/lib64/python3.9/site-packages/tables/tests/test_index_backcompat.py", line 12, in setUp
[  701s]     self.sl = self.table1.cols.var1.index.slicesize
[  701s] AttributeError: 'UnImplemented' object has no attribute 'cols'
[  701s] 
[  701s] ======================================================================
[  701s] ERROR: test02_bool (tables.tests.test_index_backcompat.Indexes2_1TestCase)
[  701s] Checking bool indexes.
[  701s] ----------------------------------------------------------------------
[  701s] Traceback (most recent call last):
[  701s]   File "/home/abuild/rpmbuild/BUILDROOT/python-tables-3.7.0-2.1.s390x/usr/lib64/python3.9/site-packages/tables/tests/test_index_backcompat.py", line 12, in setUp
[  701s]     self.sl = self.table1.cols.var1.index.slicesize
[  701s] AttributeError: 'UnImplemented' object has no attribute 'cols'
[  701s] 
[  701s] ======================================================================
[  701s] ERROR: test03_int (tables.tests.test_index_backcompat.Indexes2_1TestCase)
[  701s] Checking int indexes.
[  701s] ----------------------------------------------------------------------
[  701s] Traceback (most recent call last):
[  701s]   File "/home/abuild/rpmbuild/BUILDROOT/python-tables-3.7.0-2.1.s390x/usr/lib64/python3.9/site-packages/tables/tests/test_index_backcompat.py", line 12, in setUp
[  701s]     self.sl = self.table1.cols.var1.index.slicesize
[  701s] AttributeError: 'UnImplemented' object has no attribute 'cols'
[  701s] 
[  701s] ======================================================================
[  701s] ERROR: test04_float (tables.tests.test_index_backcompat.Indexes2_1TestCase)
[  701s] Checking float indexes.
[  701s] ----------------------------------------------------------------------
[  701s] Traceback (most recent call last):
[  701s]   File "/home/abuild/rpmbuild/BUILDROOT/python-tables-3.7.0-2.1.s390x/usr/lib64/python3.9/site-packages/tables/tests/test_index_backcompat.py", line 12, in setUp
[  701s]     self.sl = self.table1.cols.var1.index.slicesize
[  701s] AttributeError: 'UnImplemented' object has no attribute 'cols'
[  701s] 
[  701s] ----------------------------------------------------------------------
[  701s] Ran 6375 tests in 385.966s

**Comment by avalentino** [comment]
Dear @skriesch, thanks for reporting.
This issue seems to be a duplicate of #735.
Unfortunately we have not the possibility to debug on s390x so it is quite  hard to fix this issue.
If you have access to the platform, any help with this issue would be very welcome,

**Comment by skriesch** [comment]
IBM is sponsoring  mainframe VMs in the LinuxONE OSS Community Cloud for open-source projects. These systems should be also available/integrated into the CI/CD pipelines of Github. If not, then you can request systems for testing at IBM:
lyz@ibm.com

I have got also such a VM. I try to fix it.

**Comment by avalentino** [comment]
Thanks a lot @skriesch, once the fix is available I will set-up the CI also for s390x.

**Comment by matoro** [comment]
I uncommented the line in `group.py` that says "uncomment for debugging", here's a sample traceback:

```
FAIL: test00_version (__main__.Indexes2_0TestCase.test00_version)
Checking index version.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/tests/test_index_backcompat.py", line 9, in setUp
    self.table1 = self.h5file.root.table1
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/group.py", line 798, in __getattr__
    return self._f_get_child(name)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/group.py", line 685, in _f_get_child
    return self._v_file._get_node(childpath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/file.py", line 1550, in _get_node
    node = self._node_manager.get_node(nodepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/file.py", line 411, in get_node
    node = self.node_factory(key)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/group.py", line 1156, in _g_load_child
    return ChildClass(self, childname)  # uncomment for debugging
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/table.py", line 808, in __init__
    super().__init__(parentnode, name, new, filters, byteorder, _log,
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/leaf.py", line 264, in __init__
    super().__init__(parentnode, name, _log)
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/node.py", line 258, in __init__
    self._g_post_init_hook()
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/table.py", line 845, in _g_post_init_hook
    indexed = indexname in self._v_file
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/file.py", line 1997, in __contains__
    self.get_node(path)
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/file.py", line 1603, in get_node
    node = self._get_node(nodepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/file.py", line 1550, in _get_node
    node = self._node_manager.get_node(nodepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/file.py", line 411, in get_node
    node = self.node_factory(key)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/group.py", line 1151, in _g_load_child
    return ChildClass(self, childname, new=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/index.py", line 381, in __init__
    super().__init__(parentnode, name, title, new, filters)
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/group.py", line 221, in __init__
    super().__init__(parentnode, name, _log)
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/node.py", line 258, in __init__
    self._g_post_init_hook()
  File "/var/tmp/portage/dev-python/tables-3.9.1-r1/work/tables-3.9.1-python3_11/install/usr/lib/python3.11/site-packages/tables/index.py", line 409, in _g_post_init_hook
    assert self.slicesize == indices.shape[1], "Wrong slicesize"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Wrong slicesize
```

**Comment by avalentino** [comment]
@matoro thanks for the additional info, really interesting.
Would you like to submit a PR for this?
I could try to figure out where the wrong `chunksize` is originated but then I would still need someone to test it on a BE architecture.
For this reason a PR would be really appreciated.

**Comment by avalentino** [comment]
Thanks @skriesch 
I will look into it ASAP

**Comment by skriesch** [comment]
It is also possible to order multiple vms for one open source project (if you enter a number of team members as a reason).
