### ISSUE TITLE
"Resource temporarily unavailable" error while opening h5 files

### ISSUE THREAD

**Issue by aroffringa** [PyTables/PyTables#960]
In the following scenario I _sometimes_ get an H5/pytables exception:

```
f = tables.Filters(complevel=complevel, complib=complib)
ho = tables.open_file(filename, filters=f, mode='w', IO_BUFFER_SIZE=1024*1024*10, BUFFER_TIMES=500)
# Do some updates
ho.close()
# Some conditions... then reopen:
ho = tables.open_file(h5parmFile, 'r+', IO_BUFFER_SIZE=1024*1024*10, BUFFER_TIMES=500)
# Do some updates
ho.close()
# More conditions, then another reopen:
ho = tables.open_file(h5parmFile, 'r+', IO_BUFFER_SIZE=1024*1024*10, BUFFER_TIMES=500)
# Do some updates
ho.close()
```

The third call to `open_file` sometimes results in the "Resource temporarily unavailable" error below. Strangely, the second never fails. On some platforms we don't get any errors, on others we do, which could be different version of pytables or hdf5. Generally the platforms where we see this error have newer software. It occurs at least with tables version 3.7.0, using python 3.8 and Ubuntu 22. Is this a known issue, or caused by me doing something incorrectly?

I noticed https://github.com/PyTables/PyTables/issues/888 , which mentions the same issue, but there the same file is opened from two processes. I make sure that I don't do that, and as the code above shows I explicitly call the `close()` function on the table before reopening. It's somewhat hard to make a minimal example, because changing the code seems to randomly make it disappear.

```
Traceback (most recent call last):
  File "/home/offringa/.local/bin/combine_h5parms.py", line 432, in <module>
    main(args.h51, args.h52, args.outh5, args.mode, reweight=args.reweight,
  File "/home/offringa/.local/bin/combine_h5parms.py", line 367, in main
    ho = h5parm(outh5parm, readonly=False)
  File "/home/offringa/.local/lib/python3.10/site-packages/losoto/h5parm.py", line 80, in __init__
    self.H = tables.open_file(h5parmFile, 'r+', IO_BUFFER_SIZE=1024*1024*10, BUFFER_TIMES=500)
  File "/home/offringa/.local/lib/python3.10/site-packages/tables/file.py", line 300, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/offringa/.local/lib/python3.10/site-packages/tables/file.py", line 750, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 486, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 620, in H5Fopen
    unable to open file
  File "H5VLcallback.c", line 3501, in H5VL_file_open
    failed to iterate over available VOL connector plugins
  File "H5PLpath.c", line 578, in H5PL__path_table_iterate
    can't iterate over plugins in plugin path '(null)'
  File "H5PLpath.c", line 620, in H5PL__path_table_iterate_process_path
    can't open directory: /usr/local/hdf5/lib/plugin
  File "H5VLcallback.c", line 3351, in H5VL__file_open
    open failed
  File "H5VLnative_file.c", line 97, in H5VL__native_file_open
    unable to open file
  File "H5Fint.c", line 1898, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1625, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 1002, in H5FD__sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace
```

**Comment by avalentino** [comment]
Dear @aroffringa, thanks for reporting.
It don't seems to be a known issue.
Typically this kind of intermittent problem are related to some external factor (like e.g. #957) or to threading (which seems not to be the case here).
Unfortunately I do not have a solution for you right now, but if you find a way to create a reproducible example let us know and we will look at it for sure.

**Comment by eric-burel** [comment]
For me "/usr/local/hdf5/lib/plugin" doesn't exist, using Python 3.7, using latest version of tables ("*" in Pipfile).
I cannot find anyway to get it installed on Ubuntu, tried [solutions in this thread](https://forum.hdfgroup.org/t/cant-open-directory-usr-local-hdf5-lib-plugin/9738/4) (using a Python package) and in [this one](https://stackoverflow.com/questions/31719451/install-hdf5-and-pytables-in-ubuntu) (installing some packages via apt), with no success.
